# K-Nearest Neighbors Training with Polars

This notebook keeps the flow simple:
- load the prepared parquet files
- separate features and target
- validate the numeric training inputs
- train and evaluate the model
- save the model and CSV outputs

## 1. Imports and Config

In [8]:
from pathlib import Path

import polars as pl
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
from sklearn.neighbors import KNeighborsClassifier
import joblib

TRAIN_FILE = "../data/processed/train.parquet"
TEST_FILE = "../data/processed/test.parquet"
MODEL_DIR = "../model"
RESULTS_DIR = "../model/results"
TARGET_COLUMN = "admitted"
RANDOM_SEED = 42
MODEL_NAME = "knn"

Path(MODEL_DIR).mkdir(parents=True, exist_ok=True)
Path(RESULTS_DIR).mkdir(parents=True, exist_ok=True)

MODEL_FILE = Path(MODEL_DIR) / "knn_model.joblib"
RESULTS_FILE = Path(RESULTS_DIR) / "knn_results.csv"
METRICS_FILE = Path(RESULTS_DIR) / "knn_metrics.csv"

## 2. Load the Dataset

In [9]:
for required_file in [TRAIN_FILE, TEST_FILE]:
    if not Path(required_file).exists():
        raise FileNotFoundError(f"Expected parquet file at: {required_file}")

train_df = pl.read_parquet(TRAIN_FILE)
test_df = pl.read_parquet(TEST_FILE)

print(f"train shape: {train_df.shape}")
print(f"test shape: {test_df.shape}")
train_df.head()

train shape: (56, 8)
test shape: (16, 8)

shape: (5, 8)
┌─────┬─────────────┬─────────────┬───────────┬─────────────┬─────────────┬─────────────┬──────────┐
│ age ┆ length_of_s ┆ prior_admis ┆ lab_score ┆ comorbidity ┆ medications ┆ followup_ga ┆ admitted │
│ --- ┆ tay         ┆ sions       ┆ ---       ┆ _count      ┆ _count      ┆ p_days      ┆ ---      │
│ i64 ┆ ---         ┆ ---         ┆ f64       ┆ ---         ┆ ---         ┆ ---         ┆ i64      │
│     ┆ i64         ┆ i64         ┆           ┆ i64         ┆ i64         ┆ i64         ┆          │
╞═════╪═════════════╪═════════════╪═══════════╪═════════════╪═════════════╪═════════════╪══════════╡
│ 34  ┆ 2           ┆ 4           ┆ 0.47      ┆ 2           ┆ 6           ┆ 21          ┆ 1        │
│ 35  ┆ 3           ┆ 3           ┆ 0.65      ┆ 1           ┆ 2           ┆ 19          ┆ 1        │
│ 71  ┆ 7           ┆ 0           ┆ 0.41      ┆ 1           ┆ 5           ┆ 3           ┆ 1        │
│ 72  ┆ 7           ┆ 1           ┆ 0.53      ┆ 5           ┆ 3           ┆ 15          ┆ 1        │
│ 49  ┆ 8           ┆ 2           ┆ 0.65      ┆ 2           ┆ 9           ┆ 17          ┆ 1        │
└─────┴─────────────┴─────────────┴───────────┴─────────────┴─────────────┴─────────────┴──────────┘

## 3. Separate Features and Target

This notebook uses the prepared train and test parquet files exactly as they come from the upstream split notebook.

In [10]:
if TARGET_COLUMN not in train_df.columns or TARGET_COLUMN not in test_df.columns:
    raise ValueError(f"Both parquet files must include the target column: {TARGET_COLUMN}")

feature_columns = [column_name for column_name in train_df.columns if column_name != TARGET_COLUMN]

X_train = train_df.select(feature_columns)
X_test = test_df.select([column_name for column_name in test_df.columns if column_name != TARGET_COLUMN])
y_train = train_df[TARGET_COLUMN].cast(pl.Int32)
y_test = test_df[TARGET_COLUMN].cast(pl.Int32)

print(feature_columns)
print(X_train.shape)
X_train.head()

['age', 'length_of_stay', 'prior_admissions', 'lab_score', 'comorbidity_count', 'medications_count', 'followup_gap_days']
(56, 7)

shape: (5, 7)
┌─────┬────────────────┬───────────────┬───────────┬───────────────┬───────────────┬───────────────┐
│ age ┆ length_of_stay ┆ prior_admissi ┆ lab_score ┆ comorbidity_c ┆ medications_c ┆ followup_gap_ │
│ --- ┆ ---            ┆ ons           ┆ ---       ┆ ount          ┆ ount          ┆ days          │
│ i64 ┆ i64            ┆ ---           ┆ f64       ┆ ---           ┆ ---           ┆ ---           │
│     ┆                ┆ i64           ┆           ┆ i64           ┆ i64           ┆ i64           │
╞═════╪════════════════╪═══════════════╪═══════════╪═══════════════╪═══════════════╪═══════════════╡
│ 34  ┆ 2              ┆ 4             ┆ 0.47      ┆ 2             ┆ 6             ┆ 21            │
│ 35  ┆ 3              ┆ 3             ┆ 0.65      ┆ 1             ┆ 2             ┆ 19            │
│ 71  ┆ 7              ┆ 0             ┆ 0.41      ┆ 1             ┆ 5             ┆ 3             │
│ 72  ┆ 7              ┆ 1             ┆ 0.53      ┆ 5             ┆ 3             ┆ 15            │
│ 49  ┆ 8              ┆ 2             ┆ 0.65      ┆ 2             ┆ 9             ┆ 17            │
└─────┴────────────────┴───────────────┴───────────┴───────────────┴───────────────┴───────────────┘

## 4. Validate the Prepared Features

These notebooks expect the upstream split and feature-selection notebook to output numeric, model-ready feature columns.

In [11]:
test_feature_columns = [column_name for column_name in test_df.columns if column_name != TARGET_COLUMN]

if feature_columns != test_feature_columns:
    raise ValueError(
        "Train and test parquet files must have the same feature columns in the same order."
    )

non_numeric_columns = sorted(
    set(
        [column_name for column_name, dtype in X_train.schema.items() if not dtype.is_numeric()]
        + [column_name for column_name, dtype in X_test.schema.items() if not dtype.is_numeric()]
    )
)

if non_numeric_columns:
    raise ValueError(
        "The split/feature-selection notebook must output model-ready numeric features. "
        f"Non-numeric columns found: {non_numeric_columns}"
    )

print(f"validated {len(feature_columns)} numeric feature columns")

validated 7 numeric feature columns

## 5. Train the Model

In [12]:
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train.to_numpy(), y_train.to_numpy())

model

KNeighborsClassifier()

## 6. Evaluate and Save

In [13]:
probabilities = model.predict_proba(X_test.to_numpy())[:, 1]
predictions = (probabilities >= 0.5).astype(int)
actuals = y_test.to_numpy()

metrics = {
    "model": MODEL_NAME,
    "accuracy": accuracy_score(actuals, predictions),
    "precision": precision_score(actuals, predictions, zero_division=0),
    "recall": recall_score(actuals, predictions, zero_division=0),
    "roc_auc": roc_auc_score(actuals, probabilities),
}

metrics_frame = pl.DataFrame([metrics])
results_frame = test_df.with_columns(
    [
        pl.Series("actual", actuals),
        pl.Series("predicted", predictions),
        pl.Series("probability", probabilities),
        pl.lit(MODEL_NAME).alias("model"),
    ]
)

joblib.dump(model, MODEL_FILE)
metrics_frame.write_csv(METRICS_FILE)
results_frame.write_csv(RESULTS_FILE)

print(f"model saved to: {MODEL_FILE}")
print(f"metrics saved to: {METRICS_FILE}")
print(f"results saved to: {RESULTS_FILE}")
metrics_frame

model saved to: ..\model\knn_model.joblib
metrics saved to: ..\model\results\knn_metrics.csv
results saved to: ..\model\results\knn_results.csv

shape: (1, 5)
┌───────┬──────────┬───────────┬────────┬─────────┐
│ model ┆ accuracy ┆ precision ┆ recall ┆ roc_auc │
│ ---   ┆ ---      ┆ ---       ┆ ---    ┆ ---     │
│ str   ┆ f64      ┆ f64       ┆ f64    ┆ f64     │
╞═══════╪══════════╪═══════════╪════════╪═════════╡
│ knn   ┆ 0.9375   ┆ 0.9375    ┆ 1.0    ┆ 0.9     │
└───────┴──────────┴───────────┴────────┴─────────┘

## 7. Preview Results

In [14]:
results_frame.head(10)

shape: (10, 12)
┌─────┬────────────────┬────────────────┬───────────┬───┬────────┬───────────┬─────────────┬───────┐
│ age ┆ length_of_stay ┆ prior_admissio ┆ lab_score ┆ … ┆ actual ┆ predicted ┆ probability ┆ model │
│ --- ┆ ---            ┆ ns             ┆ ---       ┆   ┆ ---    ┆ ---       ┆ ---         ┆ ---   │
│ i64 ┆ i64            ┆ ---            ┆ f64       ┆   ┆ i32    ┆ i64       ┆ f64         ┆ str   │
│     ┆                ┆ i64            ┆           ┆   ┆        ┆           ┆             ┆       │
╞═════╪════════════════╪════════════════╪═══════════╪═══╪════════╪═══════════╪═════════════╪═══════╡
│ 48  ┆ 7              ┆ 3              ┆ 0.47      ┆ … ┆ 1      ┆ 1         ┆ 1.0         ┆ knn   │
│ 30  ┆ 1              ┆ 2              ┆ 0.59      ┆ … ┆ 1      ┆ 1         ┆ 0.8         ┆ knn   │
│ 53  ┆ 8              ┆ 1              ┆ 0.47      ┆ … ┆ 1      ┆ 1         ┆ 1.0         ┆ knn   │
│ 35  ┆ 2              ┆ 0              ┆ 0.59      ┆ … ┆ 1      ┆ 1         ┆ 0.8         ┆ knn   │
│ 43  ┆ 6              ┆ 0              ┆ 0.47      ┆ … ┆ 1      ┆ 1         ┆ 1.0         ┆ knn   │
│ 31  ┆ 2              ┆ 1              ┆ 0.77      ┆ … ┆ 0      ┆ 1         ┆ 0.8         ┆ knn   │
│ 34  ┆ 3              ┆ 2              ┆ 0.53      ┆ … ┆ 1      ┆ 1         ┆ 1.0         ┆ knn   │
│ 49  ┆ 7              ┆ 4              ┆ 0.59      ┆ … ┆ 1      ┆ 1         ┆ 1.0         ┆ knn   │
│ 61  ┆ 4              ┆ 1              ┆ 0.35      ┆ … ┆ 1      ┆ 1         ┆ 1.0         ┆ knn   │
│ 67  ┆ 6              ┆ 3              ┆ 0.53      ┆ … ┆ 1      ┆ 1         ┆ 1.0         ┆ knn   │
└─────┴────────────────┴────────────────┴───────────┴───┴────────┴───────────┴─────────────┴───────┘