In [1]:
import os
import polars as pl
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler, OneHotEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [2]:
df = pl.read_csv("../data/diabetic_data.csv")
df.head()

shape: (5, 50)
┌────────────┬────────────┬────────────┬────────┬───┬────────────┬────────┬────────────┬───────────┐
│ encounter_ ┆ patient_nb ┆ race       ┆ gender ┆ … ┆ metformin- ┆ change ┆ diabetesMe ┆ readmitte │
│ id         ┆ r          ┆ ---        ┆ ---    ┆   ┆ pioglitazo ┆ ---    ┆ d          ┆ d         │
│ ---        ┆ ---        ┆ str        ┆ str    ┆   ┆ ne         ┆ str    ┆ ---        ┆ ---       │
│ i64        ┆ i64        ┆            ┆        ┆   ┆ ---        ┆        ┆ str        ┆ str       │
│            ┆            ┆            ┆        ┆   ┆ str        ┆        ┆            ┆           │
╞════════════╪════════════╪════════════╪════════╪═══╪════════════╪════════╪════════════╪═══════════╡
│ 2278392    ┆ 8222157    ┆ Caucasian  ┆ Female ┆ … ┆ No         ┆ No     ┆ No         ┆ NO        │
│ 149190     ┆ 55629189   ┆ Caucasian  ┆ Female ┆ … ┆ No         ┆ Ch     ┆ Yes        ┆ >30       │
│ 64410      ┆ 86047875   ┆ AfricanAme ┆ Female ┆ … ┆ No         ┆ No     ┆ Yes        ┆ NO        │
│            ┆            ┆ rican      ┆        ┆   ┆            ┆        ┆            ┆           │
│ 500364     ┆ 82442376   ┆ Caucasian  ┆ Male   ┆ … ┆ No         ┆ Ch     ┆ Yes        ┆ NO        │
│ 16680      ┆ 42519267   ┆ Caucasian  ┆ Male   ┆ … ┆ No         ┆ Ch     ┆ Yes        ┆ NO        │
└────────────┴────────────┴────────────┴────────┴───┴────────────┴────────┴────────────┴───────────┘

In [3]:
df.describe()

shape: (9, 51)
┌────────────┬────────────┬────────────┬────────┬───┬────────────┬────────┬────────────┬───────────┐
│ statistic  ┆ encounter_ ┆ patient_nb ┆ race   ┆ … ┆ metformin- ┆ change ┆ diabetesMe ┆ readmitte │
│ ---        ┆ id         ┆ r          ┆ ---    ┆   ┆ pioglitazo ┆ ---    ┆ d          ┆ d         │
│ str        ┆ ---        ┆ ---        ┆ str    ┆   ┆ ne         ┆ str    ┆ ---        ┆ ---       │
│            ┆ f64        ┆ f64        ┆        ┆   ┆ ---        ┆        ┆ str        ┆ str       │
│            ┆            ┆            ┆        ┆   ┆ str        ┆        ┆            ┆           │
╞════════════╪════════════╪════════════╪════════╪═══╪════════════╪════════╪════════════╪═══════════╡
│ count      ┆ 101766.0   ┆ 101766.0   ┆ 101766 ┆ … ┆ 101766     ┆ 101766 ┆ 101766     ┆ 101766    │
│ null_count ┆ 0.0        ┆ 0.0        ┆ 0      ┆ … ┆ 0          ┆ 0      ┆ 0          ┆ 0         │
│ mean       ┆ 1.6520e8   ┆ 5.4330e7   ┆ null   ┆ … ┆ null       ┆ null   ┆ null       ┆ null      │
│ std        ┆ 1.0264e8   ┆ 3.8696e7   ┆ null   ┆ … ┆ null       ┆ null   ┆ null       ┆ null      │
│ min        ┆ 12522.0    ┆ 135.0      ┆ ?      ┆ … ┆ No         ┆ Ch     ┆ No         ┆ <30       │
│ 25%        ┆ 8.4960072e ┆ 2.3413212e ┆ null   ┆ … ┆ null       ┆ null   ┆ null       ┆ null      │
│            ┆ 7          ┆ 7          ┆        ┆   ┆            ┆        ┆            ┆           │
│ 50%        ┆ 1.5238968e ┆ 4.5505143e ┆ null   ┆ … ┆ null       ┆ null   ┆ null       ┆ null      │
│            ┆ 8          ┆ 7          ┆        ┆   ┆            ┆        ┆            ┆           │
│ 75%        ┆ 2.30271972 ┆ 8.7546186e ┆ null   ┆ … ┆ null       ┆ null   ┆ null       ┆ null      │
│            ┆ e8         ┆ 7          ┆        ┆   ┆            ┆        ┆            ┆           │
│ max        ┆ 4.43867222 ┆ 1.89502619 ┆ Other  ┆ … ┆ Steady     ┆ No     ┆ Yes        ┆ NO        │
│            ┆ e8         ┆ e8         ┆        ┆   ┆            ┆        ┆            ┆           │
└────────────┴────────────┴────────────┴────────┴───┴────────────┴────────┴────────────┴───────────┘

In [4]:
X = df.drop(['readmitted'])
y = df['readmitted']

ordinal_cols = ['max_glu_serum', 'A1Cresult']

max_glu_categories    = [['None', 'Norm', '>200', '>300']]
A1Cresult_categories  = [['None', 'Norm', '>7', '>8']]

all_ordinal_categories = max_glu_categories + A1Cresult_categories


# Polars equivalent of select_dtypes
numerical_cols  = [col for col, dtype in zip(X.columns, X.dtypes) 
                   if dtype in [pl.Int64, pl.Float64, pl.Int32, pl.Float32]]
categorical_cols = [col for col, dtype in zip(X.columns, X.dtypes) 
                    if dtype in [pl.Utf8, pl.String, pl.Categorical, pl.Boolean]]
categorical_cols = [c for c in categorical_cols if c not in ordinal_cols]

In [5]:
# Split Test and Training data
# Convert polars DataFrame and Series to pandas DataFrame and Series
X_train, X_test, y_train, y_test = train_test_split(X.to_pandas(),
                                                    y.to_pandas(),
                                                    test_size=0.3,
                                                    random_state=42,
                                                    stratify=y)

# Split X_train further into 70% dev and 30% validation
X_dev, X_val, y_dev, y_val = train_test_split(X_train,
                                               y_train,
                                               test_size=0.3,
                                               random_state=42,
                                               stratify=y_train)

In [6]:
pl.DataFrame(X_train).describe()

shape: (9, 50)
┌────────────┬────────────┬────────────┬───────┬───┬────────────┬────────────┬────────┬────────────┐
│ statistic  ┆ encounter_ ┆ patient_nb ┆ race  ┆ … ┆ metformin- ┆ metformin- ┆ change ┆ diabetesMe │
│ ---        ┆ id         ┆ r          ┆ ---   ┆   ┆ rosiglitaz ┆ pioglitazo ┆ ---    ┆ d          │
│ str        ┆ ---        ┆ ---        ┆ str   ┆   ┆ one        ┆ ne         ┆ str    ┆ ---        │
│            ┆ f64        ┆ f64        ┆       ┆   ┆ ---        ┆ ---        ┆        ┆ str        │
│            ┆            ┆            ┆       ┆   ┆ str        ┆ str        ┆        ┆            │
╞════════════╪════════════╪════════════╪═══════╪═══╪════════════╪════════════╪════════╪════════════╡
│ count      ┆ 71236.0    ┆ 71236.0    ┆ 71236 ┆ … ┆ 71236      ┆ 71236      ┆ 71236  ┆ 71236      │
│ null_count ┆ 0.0        ┆ 0.0        ┆ 0     ┆ … ┆ 0          ┆ 0          ┆ 0      ┆ 0          │
│ mean       ┆ 1.6518e8   ┆ 5.4216e7   ┆ null  ┆ … ┆ null       ┆ null       ┆ null   ┆ null       │
│ std        ┆ 1.0271e8   ┆ 3.8669e7   ┆ null  ┆ … ┆ null       ┆ null       ┆ null   ┆ null       │
│ min        ┆ 15738.0    ┆ 135.0      ┆ ?     ┆ … ┆ No         ┆ No         ┆ Ch     ┆ No         │
│ 25%        ┆ 8.4711426e ┆ 2.3402142e ┆ null  ┆ … ┆ null       ┆ null       ┆ null   ┆ null       │
│            ┆ 7          ┆ 7          ┆       ┆   ┆            ┆            ┆        ┆            │
│ 50%        ┆ 1.52323008 ┆ 4.5204345e ┆ null  ┆ … ┆ null       ┆ null       ┆ null   ┆ null       │
│            ┆ e8         ┆ 7          ┆       ┆   ┆            ┆            ┆        ┆            │
│ 75%        ┆ 2.30794458 ┆ 8.7419277e ┆ null  ┆ … ┆ null       ┆ null       ┆ null   ┆ null       │
│            ┆ e8         ┆ 7          ┆       ┆   ┆            ┆            ┆        ┆            │
│ max        ┆ 4.43867222 ┆ 1.89502619 ┆ Other ┆ … ┆ Steady     ┆ Steady     ┆ No     ┆ Yes        │
│            ┆ e8         ┆ e8         ┆       ┆   ┆            ┆            ┆        ┆            │
└────────────┴────────────┴────────────┴───────┴───┴────────────┴────────────┴────────┴────────────┘

In [7]:
# Build preprocessing pipeline
preprocessor = ColumnTransformer(transformers=[
    ('num', RobustScaler(), numerical_cols),
    ('ord', OrdinalEncoder(categories=all_ordinal_categories), ordinal_cols),
    ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), categorical_cols)
])

# Fit on train (dev) set only
X_dev_scaled  = preprocessor.fit_transform(X_dev)

# Transform all 3 dev, validation, and test sets
X_val_scaled  = preprocessor.transform(X_val)
X_test_scaled  = preprocessor.transform(X_test)

In [8]:
os.makedirs('../data', exist_ok=True)

# Use unscaled pandas DataFrames directly
dev_df  = pl.from_pandas(X_dev)
val_df  = pl.from_pandas(X_val)
test_df = pl.from_pandas(X_test)

# Add target column
dev_df  = dev_df.with_columns(pl.Series('readmitted', y_dev.to_list()))
val_df  = val_df.with_columns(pl.Series('readmitted', y_val.to_list()))
test_df = test_df.with_columns(pl.Series('readmitted', y_test.to_list()))

# Combine dev + val into full train
train_df = pl.concat([dev_df, val_df])

# Save all four
train_df.write_parquet('../data/train.parquet')
dev_df.write_parquet('../data/dev.parquet')
val_df.write_parquet('../data/val.parquet')
test_df.write_parquet('../data/test.parquet')

print(f"train.parquet : {train_df.shape}")
print(f"dev.parquet   : {dev_df.shape}")
print(f"val.parquet   : {val_df.shape}")
print(f"test.parquet  : {test_df.shape}")
print(f"\nSaved to: {os.path.abspath('../data/')}")

train.parquet : (71236, 50)
dev.parquet   : (49865, 50)
val.parquet   : (21371, 50)
test.parquet  : (30530, 50)

Saved to: /Users/eunsung/GitHub/dataquest-2026/data

In [9]:
files = ['train', 'dev', 'val', 'test']

for f in files:
    df = pl.read_parquet(f'../data/{f}.parquet')
    print(f'=== {f}.parquet {df.shape} ===')
    print(df.describe())
    print()

=== train.parquet (71236, 50) ===
shape: (9, 51)
┌────────────┬────────────┬────────────┬───────┬───┬────────────┬────────┬────────────┬────────────┐
│ statistic  ┆ encounter_ ┆ patient_nb ┆ race  ┆ … ┆ metformin- ┆ change ┆ diabetesMe ┆ readmitted │
│ ---        ┆ id         ┆ r          ┆ ---   ┆   ┆ pioglitazo ┆ ---    ┆ d          ┆ ---        │
│ str        ┆ ---        ┆ ---        ┆ str   ┆   ┆ ne         ┆ str    ┆ ---        ┆ str        │
│            ┆ f64        ┆ f64        ┆       ┆   ┆ ---        ┆        ┆ str        ┆            │
│            ┆            ┆            ┆       ┆   ┆ str        ┆        ┆            ┆            │
╞════════════╪════════════╪════════════╪═══════╪═══╪════════════╪════════╪════════════╪════════════╡
│ count      ┆ 71236.0    ┆ 71236.0    ┆ 71236 ┆ … ┆ 71236      ┆ 71236  ┆ 71236      ┆ 71236      │
│ null_count ┆ 0.0        ┆ 0.0        ┆ 0     ┆ … ┆ 0          ┆ 0      ┆ 0          ┆ 0          │
│ mean       ┆ 1.6518e8   ┆ 5.4216e7   ┆ null  ┆ … ┆ null       ┆ null   ┆ null       ┆ null       │
│ std        ┆ 1.0271e8   ┆ 3.8669e7   ┆ null  ┆ … ┆ null       ┆ null   ┆ null       ┆ null       │
│ min        ┆ 15738.0    ┆ 135.0      ┆ ?     ┆ … ┆ No         ┆ Ch     ┆ No         ┆ <30        │
│ 25%        ┆ 8.4711426e ┆ 2.3402142e ┆ null  ┆ … ┆ null       ┆ null   ┆ null       ┆ null       │
│            ┆ 7          ┆ 7          ┆       ┆   ┆            ┆        ┆            ┆            │
│ 50%        ┆ 1.52323008 ┆ 4.5204345e ┆ null  ┆ … ┆ null       ┆ null   ┆ null       ┆ null       │
│            ┆ e8         ┆ 7          ┆       ┆   ┆            ┆        ┆            ┆            │
│ 75%        ┆ 2.30794458 ┆ 8.7419277e ┆ null  ┆ … ┆ null       ┆ null   ┆ null       ┆ null       │
│            ┆ e8         ┆ 7          ┆       ┆   ┆            ┆        ┆            ┆            │
│ max        ┆ 4.43867222 ┆ 1.89502619 ┆ Other ┆ … ┆ Steady     ┆ No     ┆ Yes        ┆ NO         │
│            ┆ e8         ┆ e8         ┆       ┆   ┆            ┆        ┆            ┆            │
└────────────┴────────────┴────────────┴───────┴───┴────────────┴────────┴────────────┴────────────┘

=== dev.parquet (49865, 50) ===
shape: (9, 51)
┌────────────┬────────────┬────────────┬───────┬───┬────────────┬────────┬────────────┬────────────┐
│ statistic  ┆ encounter_ ┆ patient_nb ┆ race  ┆ … ┆ metformin- ┆ change ┆ diabetesMe ┆ readmitted │
│ ---        ┆ id         ┆ r          ┆ ---   ┆   ┆ pioglitazo ┆ ---    ┆ d          ┆ ---        │
│ str        ┆ ---        ┆ ---        ┆ str   ┆   ┆ ne         ┆ str    ┆ ---        ┆ str        │
│            ┆ f64        ┆ f64        ┆       ┆   ┆ ---        ┆        ┆ str        ┆            │
│            ┆            ┆            ┆       ┆   ┆ str        ┆        ┆            ┆            │
╞════════════╪════════════╪════════════╪═══════╪═══╪════════════╪════════╪════════════╪════════════╡
│ count      ┆ 49865.0    ┆ 49865.0    ┆ 49865 ┆ … ┆ 49865      ┆ 49865  ┆ 49865      ┆ 49865      │
│ null_count ┆ 0.0        ┆ 0.0        ┆ 0     ┆ … ┆ 0          ┆ 0      ┆ 0          ┆ 0          │
│ mean       ┆ 1.6526e8   ┆ 5.4165e7   ┆ null  ┆ … ┆ null       ┆ null   ┆ null       ┆ null       │
│ std        ┆ 1.0279e8   ┆ 3.8632e7   ┆ null  ┆ … ┆ null       ┆ null   ┆ null       ┆ null       │
│ min        ┆ 15738.0    ┆ 135.0      ┆ ?     ┆ … ┆ No         ┆ Ch     ┆ No         ┆ <30        │
│ 25%        ┆ 8.4687486e ┆ 2.3409549e ┆ null  ┆ … ┆ null       ┆ null   ┆ null       ┆ null       │
│            ┆ 7          ┆ 7          ┆       ┆   ┆            ┆        ┆            ┆            │
│ 50%        ┆ 1.52307102 ┆ 4.5179919e ┆ null  ┆ … ┆ null       ┆ null   ┆ null       ┆ null       │
│            ┆ e8         ┆ 7          ┆       ┆   ┆            ┆        ┆            ┆            │
│ 75%        ┆ 2.30752398 ┆ 8.7359697e ┆ null  ┆ … ┆ null       ┆ null   ┆ null       ┆ null       │
│            ┆ e8         ┆ 7          ┆       ┆   ┆            ┆        ┆            ┆            │
│ max        ┆ 4.43867222 ┆ 1.89502619 ┆ Other ┆ … ┆ Steady     ┆ No     ┆ Yes        ┆ NO         │
│            ┆ e8         ┆ e8         ┆       ┆   ┆            ┆        ┆            ┆            │
└────────────┴────────────┴────────────┴───────┴───┴────────────┴────────┴────────────┴────────────┘

=== val.parquet (21371, 50) ===
shape: (9, 51)
┌────────────┬────────────┬────────────┬───────┬───┬────────────┬────────┬────────────┬────────────┐
│ statistic  ┆ encounter_ ┆ patient_nb ┆ race  ┆ … ┆ metformin- ┆ change ┆ diabetesMe ┆ readmitted │
│ ---        ┆ id         ┆ r          ┆ ---   ┆   ┆ pioglitazo ┆ ---    ┆ d          ┆ ---        │
│ str        ┆ ---        ┆ ---        ┆ str   ┆   ┆ ne         ┆ str    ┆ ---        ┆ str        │
│            ┆ f64        ┆ f64        ┆       ┆   ┆ ---        ┆        ┆ str        ┆            │
│            ┆            ┆            ┆       ┆   ┆ str        ┆        ┆            ┆            │
╞════════════╪════════════╪════════════╪═══════╪═══╪════════════╪════════╪════════════╪════════════╡
│ count      ┆ 21371.0    ┆ 21371.0    ┆ 21371 ┆ … ┆ 21371      ┆ 21371  ┆ 21371      ┆ 21371      │
│ null_count ┆ 0.0        ┆ 0.0        ┆ 0     ┆ … ┆ 0          ┆ 0      ┆ 0          ┆ 0          │
│ mean       ┆ 1.6499e8   ┆ 5.4335e7   ┆ null  ┆ … ┆ null       ┆ null   ┆ null       ┆ null       │
│ std        ┆ 1.0253e8   ┆ 3.8755e7   ┆ null  ┆ … ┆ null       ┆ null   ┆ null       ┆ null       │
│ min        ┆ 28236.0    ┆ 135.0      ┆ ?     ┆ … ┆ No         ┆ Ch     ┆ No         ┆ <30        │
│ 25%        ┆ 8.483685e7 ┆ 2.3393565e ┆ null  ┆ … ┆ null       ┆ null   ┆ null       ┆ null       │
│            ┆            ┆ 7          ┆       ┆   ┆            ┆        ┆            ┆            │
│ 50%        ┆ 1.52382414 ┆ 4.5268443e ┆ null  ┆ … ┆ null       ┆ null   ┆ null       ┆ null       │
│            ┆ e8         ┆ 7          ┆       ┆   ┆            ┆        ┆            ┆            │
│ 75%        ┆ 2.30811054 ┆ 8.7586884e ┆ null  ┆ … ┆ null       ┆ null   ┆ null       ┆ null       │
│            ┆ e8         ┆ 7          ┆       ┆   ┆            ┆        ┆            ┆            │
│ max        ┆ 4.43857166 ┆ 1.8934943e ┆ Other ┆ … ┆ No         ┆ No     ┆ Yes        ┆ NO         │
│            ┆ e8         ┆ 8          ┆       ┆   ┆            ┆        ┆            ┆            │
└────────────┴────────────┴────────────┴───────┴───┴────────────┴────────┴────────────┴────────────┘

=== test.parquet (30530, 50) ===
shape: (9, 51)
┌────────────┬────────────┬────────────┬───────┬───┬────────────┬────────┬────────────┬────────────┐
│ statistic  ┆ encounter_ ┆ patient_nb ┆ race  ┆ … ┆ metformin- ┆ change ┆ diabetesMe ┆ readmitted │
│ ---        ┆ id         ┆ r          ┆ ---   ┆   ┆ pioglitazo ┆ ---    ┆ d          ┆ ---        │
│ str        ┆ ---        ┆ ---        ┆ str   ┆   ┆ ne         ┆ str    ┆ ---        ┆ str        │
│            ┆ f64        ┆ f64        ┆       ┆   ┆ ---        ┆        ┆ str        ┆            │
│            ┆            ┆            ┆       ┆   ┆ str        ┆        ┆            ┆            │
╞════════════╪════════════╪════════════╪═══════╪═══╪════════════╪════════╪════════════╪════════════╡
│ count      ┆ 30530.0    ┆ 30530.0    ┆ 30530 ┆ … ┆ 30530      ┆ 30530  ┆ 30530      ┆ 30530      │
│ null_count ┆ 0.0        ┆ 0.0        ┆ 0     ┆ … ┆ 0          ┆ 0      ┆ 0          ┆ 0          │
│ mean       ┆ 1.6526e8   ┆ 5.4598e7   ┆ null  ┆ … ┆ null       ┆ null   ┆ null       ┆ null       │
│ std        ┆ 1.0247e8   ┆ 3.8760e7   ┆ null  ┆ … ┆ null       ┆ null   ┆ null       ┆ null       │
│ min        ┆ 12522.0    ┆ 729.0      ┆ ?     ┆ … ┆ No         ┆ Ch     ┆ No         ┆ <30        │
│ 25%        ┆ 8.5540056e ┆ 2.343447e7 ┆ null  ┆ … ┆ null       ┆ null   ┆ null       ┆ null       │
│            ┆ 7          ┆            ┆       ┆   ┆            ┆        ┆            ┆            │
│ 50%        ┆ 1.52443602 ┆ 4.6189251e ┆ null  ┆ … ┆ null       ┆ null   ┆ null       ┆ null       │
│            ┆ e8         ┆ 7          ┆       ┆   ┆            ┆        ┆            ┆            │
│ 75%        ┆ 2.29078734 ┆ 8.7852384e ┆ null  ┆ … ┆ null       ┆ null   ┆ null       ┆ null       │
│            ┆ e8         ┆ 7          ┆       ┆   ┆            ┆        ┆            ┆            │
│ max        ┆ 4.43854148 ┆ 1.89351095 ┆ Other ┆ … ┆ No         ┆ No     ┆ Yes        ┆ NO         │
│            ┆ e8         ┆ e8         ┆       ┆   ┆            ┆        ┆            ┆            │
└────────────┴────────────┴────────────┴───────┴───┴────────────┴────────┴────────────┴────────────┘