# Import Libraries

In [20]:
import polars as pl

In [21]:
df = pl.read_csv("../data/diabetic_data.csv")

In [22]:
df.head()

shape: (5, 50)
┌────────────┬────────────┬────────────┬────────┬───┬────────────┬────────┬────────────┬───────────┐
│ encounter_ ┆ patient_nb ┆ race       ┆ gender ┆ … ┆ metformin- ┆ change ┆ diabetesMe ┆ readmitte │
│ id         ┆ r          ┆ ---        ┆ ---    ┆   ┆ pioglitazo ┆ ---    ┆ d          ┆ d         │
│ ---        ┆ ---        ┆ str        ┆ str    ┆   ┆ ne         ┆ str    ┆ ---        ┆ ---       │
│ i64        ┆ i64        ┆            ┆        ┆   ┆ ---        ┆        ┆ str        ┆ str       │
│            ┆            ┆            ┆        ┆   ┆ str        ┆        ┆            ┆           │
╞════════════╪════════════╪════════════╪════════╪═══╪════════════╪════════╪════════════╪═══════════╡
│ 2278392    ┆ 8222157    ┆ Caucasian  ┆ Female ┆ … ┆ No         ┆ No     ┆ No         ┆ NO        │
│ 149190     ┆ 55629189   ┆ Caucasian  ┆ Female ┆ … ┆ No         ┆ Ch     ┆ Yes        ┆ >30       │
│ 64410      ┆ 86047875   ┆ AfricanAme ┆ Female ┆ … ┆ No         ┆ No     ┆ Yes        ┆ NO        │
│            ┆            ┆ rican      ┆        ┆   ┆            ┆        ┆            ┆           │
│ 500364     ┆ 82442376   ┆ Caucasian  ┆ Male   ┆ … ┆ No         ┆ Ch     ┆ Yes        ┆ NO        │
│ 16680      ┆ 42519267   ┆ Caucasian  ┆ Male   ┆ … ┆ No         ┆ Ch     ┆ Yes        ┆ NO        │
└────────────┴────────────┴────────────┴────────┴───┴────────────┴────────┴────────────┴───────────┘

# Merge datasets into one

In [23]:
admission_type = pl.read_csv("../data/admission_type.csv")
admission_source = pl.read_csv("../data/admission_source.csv")
discharge_disposition = pl.read_csv("../data/discharge_disposition.csv")

In [24]:
df = df.join(admission_type, on="admission_type_id", how="full").rename({"description": "admission_type"}).drop("admission_type_id").drop("admission_type_id_right")

In [25]:
df = df.join(admission_source, on="admission_source_id", how="full").rename({"description": "admission_source"}).drop("admission_source_id").drop("admission_source_id_right")

In [26]:
df = df.join(discharge_disposition, on="discharge_disposition_id", how="full").rename({"description": "discharge_disposition"}).drop("discharge_disposition_id").drop("discharge_disposition_id_right")

In [27]:
df

shape: (101_778, 50)
┌────────────┬────────────┬───────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ encounter_ ┆ patient_nb ┆ race      ┆ gender ┆ … ┆ readmitte ┆ admission ┆ admission ┆ discharge │
│ id         ┆ r          ┆ ---       ┆ ---    ┆   ┆ d         ┆ _type     ┆ _source   ┆ _disposit │
│ ---        ┆ ---        ┆ str       ┆ str    ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ion       │
│ i64        ┆ i64        ┆           ┆        ┆   ┆ str       ┆ str       ┆ str       ┆ ---       │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ str       │
╞════════════╪════════════╪═══════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2278392    ┆ 8222157    ┆ Caucasian ┆ Female ┆ … ┆ NO        ┆ NULL      ┆ Physician ┆ Not       │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆ Referral  ┆ Mapped    │
│ 149190     ┆ 55629189   ┆ Caucasian ┆ Female ┆ … ┆ >30       ┆ Emergency ┆ Emergency ┆ Discharge │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆ Room      ┆ d to home │
│ 64410      ┆ 86047875   ┆ AfricanAm ┆ Female ┆ … ┆ NO        ┆ Emergency ┆ Emergency ┆ Discharge │
│            ┆            ┆ erican    ┆        ┆   ┆           ┆           ┆ Room      ┆ d to home │
│ 500364     ┆ 82442376   ┆ Caucasian ┆ Male   ┆ … ┆ NO        ┆ Emergency ┆ Emergency ┆ Discharge │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆ Room      ┆ d to home │
│ 16680      ┆ 42519267   ┆ Caucasian ┆ Male   ┆ … ┆ NO        ┆ Emergency ┆ Emergency ┆ Discharge │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆ Room      ┆ d to home │
│ …          ┆ …          ┆ …         ┆ …      ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ null       ┆ null       ┆ null      ┆ null   ┆ … ┆ null      ┆ null      ┆ Readmissi ┆ null      │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆ on to     ┆           │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆ Same Home ┆           │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆ Healt…    ┆           │
│ null       ┆ null       ┆ null      ┆ null   ┆ … ┆ null      ┆ null      ┆ null      ┆ Unknown/I │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ nvalid    │
│ null       ┆ null       ┆ null      ┆ null   ┆ … ┆ null      ┆ null      ┆ null      ┆ Expired;  │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ place     │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ unknown.  │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ Medica…   │
│ null       ┆ null       ┆ null      ┆ null   ┆ … ┆ null      ┆ null      ┆ null      ┆ Discharge │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ d/transfe │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ rred to a │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ Cr…       │
│ null       ┆ null       ┆ null      ┆ null   ┆ … ┆ null      ┆ null      ┆ null      ┆ Discharge │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ d/transfe │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ rred to   │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ anot…     │
└────────────┴────────────┴───────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [28]:
df = df.drop("encounter_id").drop("patient_nbr")

In [29]:
df

shape: (101_778, 48)
┌─────────────┬────────┬─────────┬────────┬───┬────────────┬─────────────┬────────────┬────────────┐
│ race        ┆ gender ┆ age     ┆ weight ┆ … ┆ readmitted ┆ admission_t ┆ admission_ ┆ discharge_ │
│ ---         ┆ ---    ┆ ---     ┆ ---    ┆   ┆ ---        ┆ ype         ┆ source     ┆ dispositio │
│ str         ┆ str    ┆ str     ┆ str    ┆   ┆ str        ┆ ---         ┆ ---        ┆ n          │
│             ┆        ┆         ┆        ┆   ┆            ┆ str         ┆ str        ┆ ---        │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ str        │
╞═════════════╪════════╪═════════╪════════╪═══╪════════════╪═════════════╪════════════╪════════════╡
│ Caucasian   ┆ Female ┆ [0-10)  ┆ ?      ┆ … ┆ NO         ┆ NULL        ┆ Physician  ┆ Not Mapped │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ Referral   ┆            │
│ Caucasian   ┆ Female ┆ [10-20) ┆ ?      ┆ … ┆ >30        ┆ Emergency   ┆ Emergency  ┆ Discharged │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ Room       ┆ to home    │
│ AfricanAmer ┆ Female ┆ [20-30) ┆ ?      ┆ … ┆ NO         ┆ Emergency   ┆ Emergency  ┆ Discharged │
│ ican        ┆        ┆         ┆        ┆   ┆            ┆             ┆ Room       ┆ to home    │
│ Caucasian   ┆ Male   ┆ [30-40) ┆ ?      ┆ … ┆ NO         ┆ Emergency   ┆ Emergency  ┆ Discharged │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ Room       ┆ to home    │
│ Caucasian   ┆ Male   ┆ [40-50) ┆ ?      ┆ … ┆ NO         ┆ Emergency   ┆ Emergency  ┆ Discharged │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ Room       ┆ to home    │
│ …           ┆ …      ┆ …       ┆ …      ┆ … ┆ …          ┆ …           ┆ …          ┆ …          │
│ null        ┆ null   ┆ null    ┆ null   ┆ … ┆ null       ┆ null        ┆ Readmissio ┆ null       │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ n to Same  ┆            │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ Home       ┆            │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ Healt…     ┆            │
│ null        ┆ null   ┆ null    ┆ null   ┆ … ┆ null       ┆ null        ┆ null       ┆ Unknown/In │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ valid      │
│ null        ┆ null   ┆ null    ┆ null   ┆ … ┆ null       ┆ null        ┆ null       ┆ Expired;   │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ place      │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ unknown.   │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ Medica…    │
│ null        ┆ null   ┆ null    ┆ null   ┆ … ┆ null       ┆ null        ┆ null       ┆ Discharged │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ /transferr │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ ed to a    │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ Cr…        │
│ null        ┆ null   ┆ null    ┆ null   ┆ … ┆ null       ┆ null        ┆ null       ┆ Discharged │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ /transferr │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ ed to      │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ anot…      │
└─────────────┴────────┴─────────┴────────┴───┴────────────┴─────────────┴────────────┴────────────┘

In [30]:
df.describe()

shape: (9, 49)
┌────────────┬────────┬────────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ race   ┆ gender     ┆ age      ┆ … ┆ readmitted ┆ admission ┆ admission ┆ discharge │
│ ---        ┆ ---    ┆ ---        ┆ ---      ┆   ┆ ---        ┆ _type     ┆ _source   ┆ _disposit │
│ str        ┆ str    ┆ str        ┆ str      ┆   ┆ str        ┆ ---       ┆ ---       ┆ ion       │
│            ┆        ┆            ┆          ┆   ┆            ┆ str       ┆ str       ┆ ---       │
│            ┆        ┆            ┆          ┆   ┆            ┆           ┆           ┆ str       │
╞════════════╪════════╪════════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 101766 ┆ 101766     ┆ 101766   ┆ … ┆ 101766     ┆ 101766    ┆ 101774    ┆ 101770    │
│ null_count ┆ 12     ┆ 12         ┆ 12       ┆ … ┆ 12         ┆ 12        ┆ 4         ┆ 8         │
│ mean       ┆ null   ┆ null       ┆ null     ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ std        ┆ null   ┆ null       ┆ null     ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ min        ┆ ?      ┆ Female     ┆ [0-10)   ┆ … ┆ <30        ┆ Elective  ┆ Born      ┆ Admitted  │
│            ┆        ┆            ┆          ┆   ┆            ┆           ┆ inside    ┆ as an     │
│            ┆        ┆            ┆          ┆   ┆            ┆           ┆ this      ┆ inpatient │
│            ┆        ┆            ┆          ┆   ┆            ┆           ┆ hospital  ┆ to th…    │
│ 25%        ┆ null   ┆ null       ┆ null     ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 50%        ┆ null   ┆ null       ┆ null     ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 75%        ┆ null   ┆ null       ┆ null     ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ max        ┆ Other  ┆ Unknown/In ┆ [90-100) ┆ … ┆ NO         ┆ Urgent    ┆ Unknown/I ┆ Unknown/I │
│            ┆        ┆ valid      ┆          ┆   ┆            ┆           ┆ nvalid    ┆ nvalid    │
└────────────┴────────┴────────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [31]:
# Delete null rows
df = df.filter(~pl.any_horizontal(pl.all().is_null()))

In [32]:
df.describe()

shape: (9, 49)
┌────────────┬────────┬────────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ race   ┆ gender     ┆ age      ┆ … ┆ readmitted ┆ admission ┆ admission ┆ discharge │
│ ---        ┆ ---    ┆ ---        ┆ ---      ┆   ┆ ---        ┆ _type     ┆ _source   ┆ _disposit │
│ str        ┆ str    ┆ str        ┆ str      ┆   ┆ str        ┆ ---       ┆ ---       ┆ ion       │
│            ┆        ┆            ┆          ┆   ┆            ┆ str       ┆ str       ┆ ---       │
│            ┆        ┆            ┆          ┆   ┆            ┆           ┆           ┆ str       │
╞════════════╪════════╪════════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 101766 ┆ 101766     ┆ 101766   ┆ … ┆ 101766     ┆ 101766    ┆ 101766    ┆ 101766    │
│ null_count ┆ 0      ┆ 0          ┆ 0        ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
│ mean       ┆ null   ┆ null       ┆ null     ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ std        ┆ null   ┆ null       ┆ null     ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ min        ┆ ?      ┆ Female     ┆ [0-10)   ┆ … ┆ <30        ┆ Elective  ┆ Clinic    ┆ Admitted  │
│            ┆        ┆            ┆          ┆   ┆            ┆           ┆ Referral  ┆ as an     │
│            ┆        ┆            ┆          ┆   ┆            ┆           ┆           ┆ inpatient │
│            ┆        ┆            ┆          ┆   ┆            ┆           ┆           ┆ to th…    │
│ 25%        ┆ null   ┆ null       ┆ null     ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 50%        ┆ null   ┆ null       ┆ null     ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 75%        ┆ null   ┆ null       ┆ null     ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ max        ┆ Other  ┆ Unknown/In ┆ [90-100) ┆ … ┆ NO         ┆ Urgent    ┆ Transfer  ┆ Still     │
│            ┆        ┆ valid      ┆          ┆   ┆            ┆           ┆ from      ┆ patient   │
│            ┆        ┆            ┆          ┆   ┆            ┆           ┆ hospital  ┆ or        │
│            ┆        ┆            ┆          ┆   ┆            ┆           ┆ inpt/sa…  ┆ expected  │
│            ┆        ┆            ┆          ┆   ┆            ┆           ┆           ┆ to r…     │
└────────────┴────────┴────────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [33]:
# Remove the unwanted feature columns
df= df.drop("weight").drop("acetohexamide").drop("tolbutamide").drop("acarbose").drop("miglitol").drop("troglitazone").drop("metformin-pioglitazone").drop("metformin-rosiglitazone").drop("glimepiride-pioglitazone").drop("glipizide-metformin").drop("tolazamide")

In [34]:
# Combine unknown race entries

df = df.with_columns(
    pl.col("race")
    .replace({
        "?": "Other",
        "Unknown/Invalid": "Other",
        "Unknown": "Other"
    })
)

In [36]:
# Combine Insurance into their categories (Public/Private)

df = df.with_columns(
    pl.col("payer_code")
    .replace({
        "MC": "Public",
        "MD": "Public",
        "SI": "Public",
        "MP": "Public",
        "FR": "Public",
        "OG": "Public",
        "DM": "Public",
        "HM": "Private",
        "BC": "Private",
        "CH": "Private",
        "CM": "Private",
        "CP": "Private",
        "PO": "Private",
        "SP": "Uninsured",
        "UN": "Uninsured",
        "OT": "Other",
        "?": "Other",
        "WC": "Other",
    })
)

In [37]:
# Combine Glucose Serum Test

df = df.with_columns(
    pl.col("max_glu_serum")
    .replace({
        ">200": "High",
        ">300": "High",
        "Norm": "Normal"
    })
)

In [38]:
df.head()

shape: (5, 37)
┌────────────┬────────┬─────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ race       ┆ gender ┆ age     ┆ time_in_ho ┆ … ┆ readmitted ┆ admission_ ┆ admission ┆ discharge │
│ ---        ┆ ---    ┆ ---     ┆ spital     ┆   ┆ ---        ┆ type       ┆ _source   ┆ _disposit │
│ str        ┆ str    ┆ str     ┆ ---        ┆   ┆ str        ┆ ---        ┆ ---       ┆ ion       │
│            ┆        ┆         ┆ i64        ┆   ┆            ┆ str        ┆ str       ┆ ---       │
│            ┆        ┆         ┆            ┆   ┆            ┆            ┆           ┆ str       │
╞════════════╪════════╪═════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ Caucasian  ┆ Female ┆ [0-10)  ┆ 1          ┆ … ┆ NO         ┆ NULL       ┆ Physician ┆ Not       │
│            ┆        ┆         ┆            ┆   ┆            ┆            ┆ Referral  ┆ Mapped    │
│ Caucasian  ┆ Female ┆ [10-20) ┆ 3          ┆ … ┆ >30        ┆ Emergency  ┆ Emergency ┆ Discharge │
│            ┆        ┆         ┆            ┆   ┆            ┆            ┆ Room      ┆ d to home │
│ AfricanAme ┆ Female ┆ [20-30) ┆ 2          ┆ … ┆ NO         ┆ Emergency  ┆ Emergency ┆ Discharge │
│ rican      ┆        ┆         ┆            ┆   ┆            ┆            ┆ Room      ┆ d to home │
│ Caucasian  ┆ Male   ┆ [30-40) ┆ 2          ┆ … ┆ NO         ┆ Emergency  ┆ Emergency ┆ Discharge │
│            ┆        ┆         ┆            ┆   ┆            ┆            ┆ Room      ┆ d to home │
│ Caucasian  ┆ Male   ┆ [40-50) ┆ 1          ┆ … ┆ NO         ┆ Emergency  ┆ Emergency ┆ Discharge │
│            ┆        ┆         ┆            ┆   ┆            ┆            ┆ Room      ┆ d to home │
└────────────┴────────┴─────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [39]:
df["payer_code"].unique().to_list()

['Uninsured', 'Other', 'Private', 'Public']

In [40]:
df["diag_1"].unique()

shape: (717,)
Series: 'diag_1' [str]
[
	"211"
	"641"
	"851"
	"163"
	"516"
	…
	"726"
	"131"
	"442"
	"374"
	"654"
]

In [41]:
# Place primary diagnoses in categories
new_diag_1 = []

for row in df["diag_1"]:
    if row.startswith("?"):
        new_diag_1.append(row)
        continue
    if row.startswith("E"):
        row_no_e = row[1:]
        num = int(float(row_no_e))
        if num == 0:
            row = "external cause status such as work, military, or volunteer activity"
        elif num in range(1,31):
            row = "activity being performed at time of injury such as sports, walking, or computer use"
        elif num in range(800,808):
            row = "railway transport accidents"
        elif num in range(810,820):
            row = "motor vehicle traffic accidents on roads or highways"   
        elif num in range(820,826):
            row = "motor vehicle accidents not related to public traffic such as off-road vehicles"
        elif num in range(826,830):
            row = "other road vehicle accidents including bicycles, animal-drawn vehicles, or animals being ridden"
        elif num in range(830,839):
            row = "water transport accidents including boats, drowning events, or falls on watercraft" 
        elif num in range(840,846):
            row = "air and space transport accidents involving aircraft or spacecraft"       
        elif num in range(846,849):
            row = "vehicle accidents occurring in industrial or commercial premises"        
        elif num == 849:
            row = "place where accident occurred such as home, street, or public building"       
        elif num in range(850,859):
            row = "accidental poisoning from drugs, medications, or biological substances"      
        elif num in range(860,870):
            row = "accidental poisoning from chemicals, gases, liquids, or other substances"    
        elif num in range(870,877):
            row = "medical or surgical care complications such as procedural injury or equipment failure"     
        elif num in range(878,880):
            row = "abnormal reaction or later complication from medical or surgical procedure"      
        elif num in range(880,889):
            row = "accidental falls such as slipping or tripping"       
        elif num in range(890,900):
            row = "accidents caused by fire or flames"            
        elif num in range(900,910):
            row = "environmental accidents such as venomous animals or natural hazards"       
        elif num in range(910,916):
            row = "accidents involving drowning, suffocation, or foreign bodies"         
        elif num in range(916,929):
            row = "other accidental injuries such as machinery accidents, firearms, explosions, burns, or electric shock"  
        elif num == 929:
            row = "late effects of previous accidental injury"
        elif num in range(930,950):
            row = "adverse effects of drugs or biological substances during therapeutic use"
        elif num in range(950,960):
            row = "suicide or self-inflicted injury"
        elif num in range(960,970):
            row = "homicide or injury inflicted by another person"
        elif num in range(970,979):
            row = "injuries due to legal intervention such as police action"
        elif num == 979:
            row = "injuries related to terrorism"
        elif num in range(980,990):
            row = "injury where intent is undetermined"
        elif num in range(990,1000):
            row = "injury resulting from war operations"
        new_diag_1.append(row)    
        continue

    if row.startswith("V"):
        row_no_v = row[1:]
        num = int(float(row_no_v))

        if num in range(1, 7):
            row = "Persons with potential health hazards related to communicable diseases"
        elif num in range(7, 10):
            row = "Persons with need for isolation, Other potential health hazards and Prophylactic measures"
        elif num in range(10, 20):
            row = "Persons with potential health hazards related to personal and family history"
        elif num in range(20, 30):
            row = "Persons encountering health services in Circumstances related to Reproduction and development"
        elif num in range(30, 40):
            row = "Live-born infants according to type of birth"
        elif num in range(40, 50):
            row = "Persons with a condition influencing their health status"
        elif num in range(50, 60):
            row = "Persons encountering health services for specific procedures and aftercare"
        elif num in range(60, 70):
            row = "Persons encountering health services in other circumstances"
        elif num in range(70, 83):
            row = "Persons without reported diagnosis encountered during examination and investigation of individuals and populations"
        elif num in range(83, 85):
            row = "Genetics"
        new_diag_1.append(row)    
        continue

    num = int(float(row))
    
    if num in range(1, 140):
        row = "infectious and parasitic diseases"
    elif num in range(140, 240):
        row = "neoplasms"
    elif num in range(240, 280):
        row = "endocrine, nutritional and metabolic diseases, and immunity disorders"
    elif num in range(280, 290):
        row = "diseases of the blood and blood-forming organs"
    elif num in range(290, 320):
        row = "mental disorders"
    elif num in range(320, 390):
        row = "diseases of the nervous system and sense organs"
    elif num in range(390, 460):
        row = "diseases of the circulatory system"
    elif num in range(460, 520):
        row = "diseases of the respiratory system"
    elif num in range(520, 580):
        row = "diseases of the digestive system"
    elif num in range(580, 630):
        row = "diseases of the genitourinary system"
    elif num in range(630, 680):
        row = "complications of pregnancy, childbirth, and the puerperium"
    elif num in range(680, 710):
        row = "diseases of the skin and subcutaneous tissue"
    elif num in range(710, 740):
        row = "diseases of the musculoskeletal system and connective tissue"
    elif num in range(740, 760):
        row = "congenital anomalies"
    elif num in range(760, 780):
        row = "certain conditions originating in the perinatal period"
    elif num in range(780, 800):
        row = "symptoms, signs, and ill-defined conditions"
    elif num in range(800, 1000):
        row = "injury and poisoning"
    new_diag_1.append(row)

new_diag_1_series = pl.Series("diag_1", new_diag_1)

print(new_diag_1_series)

df = df.with_columns(new_diag_1_series)

shape: (101_766,)
Series: 'diag_1' [str]
[
	"endocrine, nutritional and met…
	"endocrine, nutritional and met…
	"complications of pregnancy, ch…
	"infectious and parasitic disea…
	"neoplasms"
	…
	"endocrine, nutritional and met…
	"diseases of the digestive syst…
	"infectious and parasitic disea…
	"injury and poisoning"
	"diseases of the digestive syst…
]

In [43]:
# Place secondary diagnoses in categories
new_diag_2 = []

for row in df["diag_2"]:
    if row.startswith("?"):
        new_diag_2.append(row)
        continue
    if row.startswith("E"):
        row_no_e = row[1:]
        num = int(float(row_no_e))
        if num == 0:
            row = "external cause status such as work, military, or volunteer activity"
        elif num in range(1,31):
            row = "activity being performed at time of injury such as sports, walking, or computer use"
        elif num in range(800,808):
            row = "railway transport accidents"
        elif num in range(810,820):
            row = "motor vehicle traffic accidents on roads or highways"   
        elif num in range(820,826):
            row = "motor vehicle accidents not related to public traffic such as off-road vehicles"
        elif num in range(826,830):
            row = "other road vehicle accidents including bicycles, animal-drawn vehicles, or animals being ridden"
        elif num in range(830,839):
            row = "water transport accidents including boats, drowning events, or falls on watercraft" 
        elif num in range(840,846):
            row = "air and space transport accidents involving aircraft or spacecraft"       
        elif num in range(846,849):
            row = "vehicle accidents occurring in industrial or commercial premises"        
        elif num == 849:
            row = "place where accident occurred such as home, street, or public building"       
        elif num in range(850,859):
            row = "accidental poisoning from drugs, medications, or biological substances"      
        elif num in range(860,870):
            row = "accidental poisoning from chemicals, gases, liquids, or other substances"    
        elif num in range(870,877):
            row = "medical or surgical care complications such as procedural injury or equipment failure"     
        elif num in range(878,880):
            row = "abnormal reaction or later complication from medical or surgical procedure"      
        elif num in range(880,889):
            row = "accidental falls such as slipping or tripping"       
        elif num in range(890,900):
            row = "accidents caused by fire or flames"            
        elif num in range(900,910):
            row = "environmental accidents such as venomous animals or natural hazards"       
        elif num in range(910,916):
            row = "accidents involving drowning, suffocation, or foreign bodies"         
        elif num in range(916,929):
            row = "other accidental injuries such as machinery accidents, firearms, explosions, burns, or electric shock"  
        elif num == 929:
            row = "late effects of previous accidental injury"
        elif num in range(930,950):
            row = "adverse effects of drugs or biological substances during therapeutic use"
        elif num in range(950,960):
            row = "suicide or self-inflicted injury"
        elif num in range(960,970):
            row = "homicide or injury inflicted by another person"
        elif num in range(970,979):
            row = "injuries due to legal intervention such as police action"
        elif num == 979:
            row = "injuries related to terrorism"
        elif num in range(980,990):
            row = "injury where intent is undetermined"
        elif num in range(990,1000):
            row = "injury resulting from war operations"
        new_diag_2.append(row)    
        continue

    if row.startswith("V"):
        row_no_v = row[1:]
        num = int(float(row_no_v))

        if num in range(1, 7):
            row = "Persons with potential health hazards related to communicable diseases"
        elif num in range(7, 10):
            row = "Persons with need for isolation, Other potential health hazards and Prophylactic measures"
        elif num in range(10, 20):
            row = "Persons with potential health hazards related to personal and family history"
        elif num in range(20, 30):
            row = "Persons encountering health services in Circumstances related to Reproduction and development"
        elif num in range(30, 40):
            row = "Live-born infants according to type of birth"
        elif num in range(40, 50):
            row = "Persons with a condition influencing their health status"
        elif num in range(50, 60):
            row = "Persons encountering health services for specific procedures and aftercare"
        elif num in range(60, 70):
            row = "Persons encountering health services in other circumstances"
        elif num in range(70, 83):
            row = "Persons without reported diagnosis encountered during examination and investigation of individuals and populations"
        elif num in range(83, 85):
            row = "Genetics"
        new_diag_2.append(row)    
        continue

    num = int(float(row))
    
    if num in range(1, 140):
        row = "infectious and parasitic diseases"
    elif num in range(140, 240):
        row = "neoplasms"
    elif num in range(240, 280):
        row = "endocrine, nutritional and metabolic diseases, and immunity disorders"
    elif num in range(280, 290):
        row = "diseases of the blood and blood-forming organs"
    elif num in range(290, 320):
        row = "mental disorders"
    elif num in range(320, 390):
        row = "diseases of the nervous system and sense organs"
    elif num in range(390, 460):
        row = "diseases of the circulatory system"
    elif num in range(460, 520):
        row = "diseases of the respiratory system"
    elif num in range(520, 580):
        row = "diseases of the digestive system"
    elif num in range(580, 630):
        row = "diseases of the genitourinary system"
    elif num in range(630, 680):
        row = "complications of pregnancy, childbirth, and the puerperium"
    elif num in range(680, 710):
        row = "diseases of the skin and subcutaneous tissue"
    elif num in range(710, 740):
        row = "diseases of the musculoskeletal system and connective tissue"
    elif num in range(740, 760):
        row = "congenital anomalies"
    elif num in range(760, 780):
        row = "certain conditions originating in the perinatal period"
    elif num in range(780, 800):
        row = "symptoms, signs, and ill-defined conditions"
    elif num in range(800, 1000):
        row = "injury and poisoning"
    new_diag_2.append(row)

    

new_diag_2_series = pl.Series("diag_2", new_diag_2)

print(new_diag_2_series)

df = df.with_columns(new_diag_2_series)

shape: (101_766,)
Series: 'diag_2' [str]
[
	"?"
	"endocrine, nutritional and met…
	"endocrine, nutritional and met…
	"endocrine, nutritional and met…
	"neoplasms"
	…
	"mental disorders"
	"endocrine, nutritional and met…
	"diseases of the genitourinary …
	"diseases of the blood and bloo…
	"diseases of the digestive syst…
]

In [45]:
# Place additional secondary diagnoses in categories
new_diag_3 = []

for row in df["diag_3"]:
    if row.startswith("?"):
        new_diag_3.append(row)
        continue
    if row.startswith("E"):
        row_no_e = row[1:]
        num = int(float(row_no_e))
        if num == 0:
            row = "external cause status such as work, military, or volunteer activity"
        elif num in range(1,31):
            row = "activity being performed at time of injury such as sports, walking, or computer use"
        elif num in range(800,808):
            row = "railway transport accidents"
        elif num in range(810,820):
            row = "motor vehicle traffic accidents on roads or highways"   
        elif num in range(820,826):
            row = "motor vehicle accidents not related to public traffic such as off-road vehicles"
        elif num in range(826,830):
            row = "other road vehicle accidents including bicycles, animal-drawn vehicles, or animals being ridden"
        elif num in range(830,839):
            row = "water transport accidents including boats, drowning events, or falls on watercraft" 
        elif num in range(840,846):
            row = "air and space transport accidents involving aircraft or spacecraft"       
        elif num in range(846,849):
            row = "vehicle accidents occurring in industrial or commercial premises"        
        elif num == 849:
            row = "place where accident occurred such as home, street, or public building"       
        elif num in range(850,859):
            row = "accidental poisoning from drugs, medications, or biological substances"      
        elif num in range(860,870):
            row = "accidental poisoning from chemicals, gases, liquids, or other substances"    
        elif num in range(870,877):
            row = "medical or surgical care complications such as procedural injury or equipment failure"     
        elif num in range(878,880):
            row = "abnormal reaction or later complication from medical or surgical procedure"      
        elif num in range(880,889):
            row = "accidental falls such as slipping or tripping"       
        elif num in range(890,900):
            row = "accidents caused by fire or flames"            
        elif num in range(900,910):
            row = "environmental accidents such as venomous animals or natural hazards"       
        elif num in range(910,916):
            row = "accidents involving drowning, suffocation, or foreign bodies"         
        elif num in range(916,929):
            row = "other accidental injuries such as machinery accidents, firearms, explosions, burns, or electric shock"  
        elif num == 929:
            row = "late effects of previous accidental injury"
        elif num in range(930,950):
            row = "adverse effects of drugs or biological substances during therapeutic use"
        elif num in range(950,960):
            row = "suicide or self-inflicted injury"
        elif num in range(960,970):
            row = "homicide or injury inflicted by another person"
        elif num in range(970,979):
            row = "injuries due to legal intervention such as police action"
        elif num == 979:
            row = "injuries related to terrorism"
        elif num in range(980,990):
            row = "injury where intent is undetermined"
        elif num in range(990,1000):
            row = "injury resulting from war operations"
        new_diag_3.append(row)    
        continue

    if row.startswith("V"):
        row_no_v = row[1:]
        num = int(float(row_no_v))

        if num in range(1, 7):
            row = "Persons with potential health hazards related to communicable diseases"
        elif num in range(7, 10):
            row = "Persons with need for isolation, Other potential health hazards and Prophylactic measures"
        elif num in range(10, 20):
            row = "Persons with potential health hazards related to personal and family history"
        elif num in range(20, 30):
            row = "Persons encountering health services in Circumstances related to Reproduction and development"
        elif num in range(30, 40):
            row = "Live-born infants according to type of birth"
        elif num in range(40, 50):
            row = "Persons with a condition influencing their health status"
        elif num in range(50, 60):
            row = "Persons encountering health services for specific procedures and aftercare"
        elif num in range(60, 70):
            row = "Persons encountering health services in other circumstances"
        elif num in range(70, 83):
            row = "Persons without reported diagnosis encountered during examination and investigation of individuals and populations"
        elif num in range(83, 85):
            row = "Genetics"
        new_diag_3.append(row)    
        continue

    num = int(float(row))
    
    if num in range(1, 140):
        row = "infectious and parasitic diseases"
    elif num in range(140, 240):
        row = "neoplasms"
    elif num in range(240, 280):
        row = "endocrine, nutritional and metabolic diseases, and immunity disorders"
    elif num in range(280, 290):
        row = "diseases of the blood and blood-forming organs"
    elif num in range(290, 320):
        row = "mental disorders"
    elif num in range(320, 390):
        row = "diseases of the nervous system and sense organs"
    elif num in range(390, 460):
        row = "diseases of the circulatory system"
    elif num in range(460, 520):
        row = "diseases of the respiratory system"
    elif num in range(520, 580):
        row = "diseases of the digestive system"
    elif num in range(580, 630):
        row = "diseases of the genitourinary system"
    elif num in range(630, 680):
        row = "complications of pregnancy, childbirth, and the puerperium"
    elif num in range(680, 710):
        row = "diseases of the skin and subcutaneous tissue"
    elif num in range(710, 740):
        row = "diseases of the musculoskeletal system and connective tissue"
    elif num in range(740, 760):
        row = "congenital anomalies"
    elif num in range(760, 780):
        row = "certain conditions originating in the perinatal period"
    elif num in range(780, 800):
        row = "symptoms, signs, and ill-defined conditions"
    elif num in range(800, 1000):
        row = "injury and poisoning"
    new_diag_3.append(row)

    

new_diag_3_series = pl.Series("diag_3", new_diag_3)

print(new_diag_3_series)

df = df.with_columns(new_diag_3_series)

shape: (101_766,)
Series: 'diag_3' [str]
[
	"?"
	"endocrine, nutritional and met…
	"Persons encountering health se…
	"diseases of the circulatory sy…
	"endocrine, nutritional and met…
	…
	"diseases of the circulatory sy…
	"symptoms, signs, and ill-defin…
	"mental disorders"
	"injury and poisoning"
	"symptoms, signs, and ill-defin…
]

In [46]:
df.head()

shape: (5, 37)
┌────────────┬────────┬─────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ race       ┆ gender ┆ age     ┆ time_in_ho ┆ … ┆ readmitted ┆ admission_ ┆ admission ┆ discharge │
│ ---        ┆ ---    ┆ ---     ┆ spital     ┆   ┆ ---        ┆ type       ┆ _source   ┆ _disposit │
│ str        ┆ str    ┆ str     ┆ ---        ┆   ┆ str        ┆ ---        ┆ ---       ┆ ion       │
│            ┆        ┆         ┆ i64        ┆   ┆            ┆ str        ┆ str       ┆ ---       │
│            ┆        ┆         ┆            ┆   ┆            ┆            ┆           ┆ str       │
╞════════════╪════════╪═════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ Caucasian  ┆ Female ┆ [0-10)  ┆ 1          ┆ … ┆ NO         ┆ NULL       ┆ Physician ┆ Not       │
│            ┆        ┆         ┆            ┆   ┆            ┆            ┆ Referral  ┆ Mapped    │
│ Caucasian  ┆ Female ┆ [10-20) ┆ 3          ┆ … ┆ >30        ┆ Emergency  ┆ Emergency ┆ Discharge │
│            ┆        ┆         ┆            ┆   ┆            ┆            ┆ Room      ┆ d to home │
│ AfricanAme ┆ Female ┆ [20-30) ┆ 2          ┆ … ┆ NO         ┆ Emergency  ┆ Emergency ┆ Discharge │
│ rican      ┆        ┆         ┆            ┆   ┆            ┆            ┆ Room      ┆ d to home │
│ Caucasian  ┆ Male   ┆ [30-40) ┆ 2          ┆ … ┆ NO         ┆ Emergency  ┆ Emergency ┆ Discharge │
│            ┆        ┆         ┆            ┆   ┆            ┆            ┆ Room      ┆ d to home │
│ Caucasian  ┆ Male   ┆ [40-50) ┆ 1          ┆ … ┆ NO         ┆ Emergency  ┆ Emergency ┆ Discharge │
│            ┆        ┆         ┆            ┆   ┆            ┆            ┆ Room      ┆ d to home │
└────────────┴────────┴─────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘