# Import Libraries

In [79]:
import polars as pl

In [80]:
df = pl.read_csv("../diabetic_data.csv")

In [81]:
df.head()

shape: (5, 50)
┌────────────┬────────────┬────────────┬────────┬───┬────────────┬────────┬────────────┬───────────┐
│ encounter_ ┆ patient_nb ┆ race       ┆ gender ┆ … ┆ metformin- ┆ change ┆ diabetesMe ┆ readmitte │
│ id         ┆ r          ┆ ---        ┆ ---    ┆   ┆ pioglitazo ┆ ---    ┆ d          ┆ d         │
│ ---        ┆ ---        ┆ str        ┆ str    ┆   ┆ ne         ┆ str    ┆ ---        ┆ ---       │
│ i64        ┆ i64        ┆            ┆        ┆   ┆ ---        ┆        ┆ str        ┆ str       │
│            ┆            ┆            ┆        ┆   ┆ str        ┆        ┆            ┆           │
╞════════════╪════════════╪════════════╪════════╪═══╪════════════╪════════╪════════════╪═══════════╡
│ 2278392    ┆ 8222157    ┆ Caucasian  ┆ Female ┆ … ┆ No         ┆ No     ┆ No         ┆ NO        │
│ 149190     ┆ 55629189   ┆ Caucasian  ┆ Female ┆ … ┆ No         ┆ Ch     ┆ Yes        ┆ >30       │
│ 64410      ┆ 86047875   ┆ AfricanAme ┆ Female ┆ … ┆ No         ┆ No     ┆ Yes        ┆ NO        │
│            ┆            ┆ rican      ┆        ┆   ┆            ┆        ┆            ┆           │
│ 500364     ┆ 82442376   ┆ Caucasian  ┆ Male   ┆ … ┆ No         ┆ Ch     ┆ Yes        ┆ NO        │
│ 16680      ┆ 42519267   ┆ Caucasian  ┆ Male   ┆ … ┆ No         ┆ Ch     ┆ Yes        ┆ NO        │
└────────────┴────────────┴────────────┴────────┴───┴────────────┴────────┴────────────┴───────────┘

# Merge datasets into one

In [82]:
admission_type = pl.read_csv("../admission_type.csv")
admission_source = pl.read_csv("../admission_source.csv")
discharge_disposition = pl.read_csv("../discharge_disposition.csv")

In [83]:
df = df.join(admission_type, on="admission_type_id", how="full").rename({"description": "admission_type"}).drop("admission_type_id").drop("admission_type_id_right")

In [84]:
df = df.join(admission_source, on="admission_source_id", how="full").rename({"description": "admission_source"}).drop("admission_source_id").drop("admission_source_id_right")

In [85]:
df = df.join(discharge_disposition, on="discharge_disposition_id", how="full").rename({"description": "discharge_disposition"}).drop("discharge_disposition_id").drop("discharge_disposition_id_right")

In [86]:
df

shape: (101_778, 50)
┌────────────┬────────────┬───────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ encounter_ ┆ patient_nb ┆ race      ┆ gender ┆ … ┆ readmitte ┆ admission ┆ admission ┆ discharge │
│ id         ┆ r          ┆ ---       ┆ ---    ┆   ┆ d         ┆ _type     ┆ _source   ┆ _disposit │
│ ---        ┆ ---        ┆ str       ┆ str    ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ion       │
│ i64        ┆ i64        ┆           ┆        ┆   ┆ str       ┆ str       ┆ str       ┆ ---       │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ str       │
╞════════════╪════════════╪═══════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2278392    ┆ 8222157    ┆ Caucasian ┆ Female ┆ … ┆ NO        ┆ NULL      ┆ Physician ┆ Not       │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆ Referral  ┆ Mapped    │
│ 149190     ┆ 55629189   ┆ Caucasian ┆ Female ┆ … ┆ >30       ┆ Emergency ┆ Emergency ┆ Discharge │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆ Room      ┆ d to home │
│ 64410      ┆ 86047875   ┆ AfricanAm ┆ Female ┆ … ┆ NO        ┆ Emergency ┆ Emergency ┆ Discharge │
│            ┆            ┆ erican    ┆        ┆   ┆           ┆           ┆ Room      ┆ d to home │
│ 500364     ┆ 82442376   ┆ Caucasian ┆ Male   ┆ … ┆ NO        ┆ Emergency ┆ Emergency ┆ Discharge │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆ Room      ┆ d to home │
│ 16680      ┆ 42519267   ┆ Caucasian ┆ Male   ┆ … ┆ NO        ┆ Emergency ┆ Emergency ┆ Discharge │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆ Room      ┆ d to home │
│ …          ┆ …          ┆ …         ┆ …      ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ null       ┆ null       ┆ null      ┆ null   ┆ … ┆ null      ┆ null      ┆ Born      ┆ null      │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆ inside    ┆           │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆ this      ┆           │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆ hospital  ┆           │
│ null       ┆ null       ┆ null      ┆ null   ┆ … ┆ null      ┆ null      ┆ null      ┆ Expired;  │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ place     │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ unknown.  │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ Medica…   │
│ null       ┆ null       ┆ null      ┆ null   ┆ … ┆ null      ┆ null      ┆ null      ┆ Discharge │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ d/transfe │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ rred to a │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ Cr…       │
│ null       ┆ null       ┆ null      ┆ null   ┆ … ┆ null      ┆ null      ┆ null      ┆ Unknown/I │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ nvalid    │
│ null       ┆ null       ┆ null      ┆ null   ┆ … ┆ null      ┆ null      ┆ null      ┆ Discharge │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ d/transfe │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ rred to   │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ anot…     │
└────────────┴────────────┴───────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [88]:
df = df.drop("encounter_id").drop("patient_nbr")

In [89]:
df

shape: (101_778, 48)
┌─────────────┬────────┬─────────┬────────┬───┬────────────┬─────────────┬────────────┬────────────┐
│ race        ┆ gender ┆ age     ┆ weight ┆ … ┆ readmitted ┆ admission_t ┆ admission_ ┆ discharge_ │
│ ---         ┆ ---    ┆ ---     ┆ ---    ┆   ┆ ---        ┆ ype         ┆ source     ┆ dispositio │
│ str         ┆ str    ┆ str     ┆ str    ┆   ┆ str        ┆ ---         ┆ ---        ┆ n          │
│             ┆        ┆         ┆        ┆   ┆            ┆ str         ┆ str        ┆ ---        │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ str        │
╞═════════════╪════════╪═════════╪════════╪═══╪════════════╪═════════════╪════════════╪════════════╡
│ Caucasian   ┆ Female ┆ [0-10)  ┆ ?      ┆ … ┆ NO         ┆ NULL        ┆ Physician  ┆ Not Mapped │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ Referral   ┆            │
│ Caucasian   ┆ Female ┆ [10-20) ┆ ?      ┆ … ┆ >30        ┆ Emergency   ┆ Emergency  ┆ Discharged │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ Room       ┆ to home    │
│ AfricanAmer ┆ Female ┆ [20-30) ┆ ?      ┆ … ┆ NO         ┆ Emergency   ┆ Emergency  ┆ Discharged │
│ ican        ┆        ┆         ┆        ┆   ┆            ┆             ┆ Room       ┆ to home    │
│ Caucasian   ┆ Male   ┆ [30-40) ┆ ?      ┆ … ┆ NO         ┆ Emergency   ┆ Emergency  ┆ Discharged │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ Room       ┆ to home    │
│ Caucasian   ┆ Male   ┆ [40-50) ┆ ?      ┆ … ┆ NO         ┆ Emergency   ┆ Emergency  ┆ Discharged │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ Room       ┆ to home    │
│ …           ┆ …      ┆ …       ┆ …      ┆ … ┆ …          ┆ …           ┆ …          ┆ …          │
│ null        ┆ null   ┆ null    ┆ null   ┆ … ┆ null       ┆ null        ┆ Born       ┆ null       │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ inside     ┆            │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ this       ┆            │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ hospital   ┆            │
│ null        ┆ null   ┆ null    ┆ null   ┆ … ┆ null       ┆ null        ┆ null       ┆ Expired;   │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ place      │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ unknown.   │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ Medica…    │
│ null        ┆ null   ┆ null    ┆ null   ┆ … ┆ null       ┆ null        ┆ null       ┆ Discharged │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ /transferr │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ ed to a    │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ Cr…        │
│ null        ┆ null   ┆ null    ┆ null   ┆ … ┆ null       ┆ null        ┆ null       ┆ Unknown/In │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ valid      │
│ null        ┆ null   ┆ null    ┆ null   ┆ … ┆ null       ┆ null        ┆ null       ┆ Discharged │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ /transferr │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ ed to      │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ anot…      │
└─────────────┴────────┴─────────┴────────┴───┴────────────┴─────────────┴────────────┴────────────┘

In [90]:
df.describe()

shape: (9, 49)
┌────────────┬────────┬────────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ race   ┆ gender     ┆ age      ┆ … ┆ readmitted ┆ admission ┆ admission ┆ discharge │
│ ---        ┆ ---    ┆ ---        ┆ ---      ┆   ┆ ---        ┆ _type     ┆ _source   ┆ _disposit │
│ str        ┆ str    ┆ str        ┆ str      ┆   ┆ str        ┆ ---       ┆ ---       ┆ ion       │
│            ┆        ┆            ┆          ┆   ┆            ┆ str       ┆ str       ┆ ---       │
│            ┆        ┆            ┆          ┆   ┆            ┆           ┆           ┆ str       │
╞════════════╪════════╪════════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 101766 ┆ 101766     ┆ 101766   ┆ … ┆ 101766     ┆ 101766    ┆ 101774    ┆ 101770    │
│ null_count ┆ 12     ┆ 12         ┆ 12       ┆ … ┆ 12         ┆ 12        ┆ 4         ┆ 8         │
│ mean       ┆ null   ┆ null       ┆ null     ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ std        ┆ null   ┆ null       ┆ null     ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ min        ┆ ?      ┆ Female     ┆ [0-10)   ┆ … ┆ <30        ┆ Elective  ┆ Born      ┆ Admitted  │
│            ┆        ┆            ┆          ┆   ┆            ┆           ┆ inside    ┆ as an     │
│            ┆        ┆            ┆          ┆   ┆            ┆           ┆ this      ┆ inpatient │
│            ┆        ┆            ┆          ┆   ┆            ┆           ┆ hospital  ┆ to th…    │
│ 25%        ┆ null   ┆ null       ┆ null     ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 50%        ┆ null   ┆ null       ┆ null     ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 75%        ┆ null   ┆ null       ┆ null     ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ max        ┆ Other  ┆ Unknown/In ┆ [90-100) ┆ … ┆ NO         ┆ Urgent    ┆ Unknown/I ┆ Unknown/I │
│            ┆        ┆ valid      ┆          ┆   ┆            ┆           ┆ nvalid    ┆ nvalid    │
└────────────┴────────┴────────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [97]:
# Delete null rows
df = df.filter(~pl.any_horizontal(pl.all().is_null()))

In [98]:
df.describe()

shape: (9, 49)
┌────────────┬──────┬────────┬──────┬───┬────────────┬───────────────┬──────────────┬──────────────┐
│ statistic  ┆ race ┆ gender ┆ age  ┆ … ┆ readmitted ┆ admission_typ ┆ admission_so ┆ discharge_di │
│ ---        ┆ ---  ┆ ---    ┆ ---  ┆   ┆ ---        ┆ e             ┆ urce         ┆ sposition    │
│ str        ┆ str  ┆ str    ┆ str  ┆   ┆ str        ┆ ---           ┆ ---          ┆ ---          │
│            ┆      ┆        ┆      ┆   ┆            ┆ str           ┆ str          ┆ str          │
╞════════════╪══════╪════════╪══════╪═══╪════════════╪═══════════════╪══════════════╪══════════════╡
│ count      ┆ 0    ┆ 0      ┆ 0    ┆ … ┆ 0          ┆ 0             ┆ 0            ┆ 0            │
│ null_count ┆ 0    ┆ 0      ┆ 0    ┆ … ┆ 0          ┆ 0             ┆ 0            ┆ 0            │
│ mean       ┆ null ┆ null   ┆ null ┆ … ┆ null       ┆ null          ┆ null         ┆ null         │
│ std        ┆ null ┆ null   ┆ null ┆ … ┆ null       ┆ null          ┆ null         ┆ null         │
│ min        ┆ null ┆ null   ┆ null ┆ … ┆ null       ┆ null          ┆ null         ┆ null         │
│ 25%        ┆ null ┆ null   ┆ null ┆ … ┆ null       ┆ null          ┆ null         ┆ null         │
│ 50%        ┆ null ┆ null   ┆ null ┆ … ┆ null       ┆ null          ┆ null         ┆ null         │
│ 75%        ┆ null ┆ null   ┆ null ┆ … ┆ null       ┆ null          ┆ null         ┆ null         │
│ max        ┆ null ┆ null   ┆ null ┆ … ┆ null       ┆ null          ┆ null         ┆ null         │
└────────────┴──────┴────────┴──────┴───┴────────────┴───────────────┴──────────────┴──────────────┘