# Import Libraries

In [169]:
import polars as pl
import numpy as np

In [170]:
df = pl.read_csv("../diabetic_data.csv")

In [171]:
df.head()

shape: (5, 50)
┌────────────┬────────────┬────────────┬────────┬───┬────────────┬────────┬────────────┬───────────┐
│ encounter_ ┆ patient_nb ┆ race       ┆ gender ┆ … ┆ metformin- ┆ change ┆ diabetesMe ┆ readmitte │
│ id         ┆ r          ┆ ---        ┆ ---    ┆   ┆ pioglitazo ┆ ---    ┆ d          ┆ d         │
│ ---        ┆ ---        ┆ str        ┆ str    ┆   ┆ ne         ┆ str    ┆ ---        ┆ ---       │
│ i64        ┆ i64        ┆            ┆        ┆   ┆ ---        ┆        ┆ str        ┆ str       │
│            ┆            ┆            ┆        ┆   ┆ str        ┆        ┆            ┆           │
╞════════════╪════════════╪════════════╪════════╪═══╪════════════╪════════╪════════════╪═══════════╡
│ 2278392    ┆ 8222157    ┆ Caucasian  ┆ Female ┆ … ┆ No         ┆ No     ┆ No         ┆ NO        │
│ 149190     ┆ 55629189   ┆ Caucasian  ┆ Female ┆ … ┆ No         ┆ Ch     ┆ Yes        ┆ >30       │
│ 64410      ┆ 86047875   ┆ AfricanAme ┆ Female ┆ … ┆ No         ┆ No     ┆ Yes        ┆ NO        │
│            ┆            ┆ rican      ┆        ┆   ┆            ┆        ┆            ┆           │
│ 500364     ┆ 82442376   ┆ Caucasian  ┆ Male   ┆ … ┆ No         ┆ Ch     ┆ Yes        ┆ NO        │
│ 16680      ┆ 42519267   ┆ Caucasian  ┆ Male   ┆ … ┆ No         ┆ Ch     ┆ Yes        ┆ NO        │
└────────────┴────────────┴────────────┴────────┴───┴────────────┴────────┴────────────┴───────────┘

# Merge datasets into one

In [172]:
admission_type = pl.read_csv("../admission_type.csv")
admission_source = pl.read_csv("../admission_source.csv")
discharge_disposition = pl.read_csv("../discharge_disposition.csv")

In [173]:
df = df.join(admission_type, on="admission_type_id", how="full").rename({"description": "admission_type"}).drop("admission_type_id").drop("admission_type_id_right")

In [174]:
df = df.join(admission_source, on="admission_source_id", how="full").rename({"description": "admission_source"}).drop("admission_source_id").drop("admission_source_id_right")

In [175]:
df = df.join(discharge_disposition, on="discharge_disposition_id", how="full").rename({"description": "discharge_disposition"}).drop("discharge_disposition_id").drop("discharge_disposition_id_right")

In [176]:
df

shape: (101_778, 50)
┌────────────┬────────────┬───────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ encounter_ ┆ patient_nb ┆ race      ┆ gender ┆ … ┆ readmitte ┆ admission ┆ admission ┆ discharge │
│ id         ┆ r          ┆ ---       ┆ ---    ┆   ┆ d         ┆ _type     ┆ _source   ┆ _disposit │
│ ---        ┆ ---        ┆ str       ┆ str    ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ion       │
│ i64        ┆ i64        ┆           ┆        ┆   ┆ str       ┆ str       ┆ str       ┆ ---       │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ str       │
╞════════════╪════════════╪═══════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2278392    ┆ 8222157    ┆ Caucasian ┆ Female ┆ … ┆ NO        ┆ NULL      ┆ Physician ┆ Not       │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆ Referral  ┆ Mapped    │
│ 149190     ┆ 55629189   ┆ Caucasian ┆ Female ┆ … ┆ >30       ┆ Emergency ┆ Emergency ┆ Discharge │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆ Room      ┆ d to home │
│ 64410      ┆ 86047875   ┆ AfricanAm ┆ Female ┆ … ┆ NO        ┆ Emergency ┆ Emergency ┆ Discharge │
│            ┆            ┆ erican    ┆        ┆   ┆           ┆           ┆ Room      ┆ d to home │
│ 500364     ┆ 82442376   ┆ Caucasian ┆ Male   ┆ … ┆ NO        ┆ Emergency ┆ Emergency ┆ Discharge │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆ Room      ┆ d to home │
│ 16680      ┆ 42519267   ┆ Caucasian ┆ Male   ┆ … ┆ NO        ┆ Emergency ┆ Emergency ┆ Discharge │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆ Room      ┆ d to home │
│ …          ┆ …          ┆ …         ┆ …      ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ null       ┆ null       ┆ null      ┆ null   ┆ … ┆ null      ┆ null      ┆ Premature ┆ null      │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆ Delivery  ┆           │
│ null       ┆ null       ┆ null      ┆ null   ┆ … ┆ null      ┆ null      ┆ null      ┆ Unknown/I │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ nvalid    │
│ null       ┆ null       ┆ null      ┆ null   ┆ … ┆ null      ┆ null      ┆ null      ┆ Discharge │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ d/transfe │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ rred to a │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ Cr…       │
│ null       ┆ null       ┆ null      ┆ null   ┆ … ┆ null      ┆ null      ┆ null      ┆ Discharge │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ d/transfe │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ rred to   │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ anot…     │
│ null       ┆ null       ┆ null      ┆ null   ┆ … ┆ null      ┆ null      ┆ null      ┆ Expired;  │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ place     │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ unknown.  │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ Medica…   │
└────────────┴────────────┴───────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [177]:
df = df.drop("encounter_id").drop("patient_nbr")

In [178]:
df

shape: (101_778, 48)
┌─────────────┬────────┬─────────┬────────┬───┬────────────┬─────────────┬────────────┬────────────┐
│ race        ┆ gender ┆ age     ┆ weight ┆ … ┆ readmitted ┆ admission_t ┆ admission_ ┆ discharge_ │
│ ---         ┆ ---    ┆ ---     ┆ ---    ┆   ┆ ---        ┆ ype         ┆ source     ┆ dispositio │
│ str         ┆ str    ┆ str     ┆ str    ┆   ┆ str        ┆ ---         ┆ ---        ┆ n          │
│             ┆        ┆         ┆        ┆   ┆            ┆ str         ┆ str        ┆ ---        │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ str        │
╞═════════════╪════════╪═════════╪════════╪═══╪════════════╪═════════════╪════════════╪════════════╡
│ Caucasian   ┆ Female ┆ [0-10)  ┆ ?      ┆ … ┆ NO         ┆ NULL        ┆ Physician  ┆ Not Mapped │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ Referral   ┆            │
│ Caucasian   ┆ Female ┆ [10-20) ┆ ?      ┆ … ┆ >30        ┆ Emergency   ┆ Emergency  ┆ Discharged │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ Room       ┆ to home    │
│ AfricanAmer ┆ Female ┆ [20-30) ┆ ?      ┆ … ┆ NO         ┆ Emergency   ┆ Emergency  ┆ Discharged │
│ ican        ┆        ┆         ┆        ┆   ┆            ┆             ┆ Room       ┆ to home    │
│ Caucasian   ┆ Male   ┆ [30-40) ┆ ?      ┆ … ┆ NO         ┆ Emergency   ┆ Emergency  ┆ Discharged │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ Room       ┆ to home    │
│ Caucasian   ┆ Male   ┆ [40-50) ┆ ?      ┆ … ┆ NO         ┆ Emergency   ┆ Emergency  ┆ Discharged │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ Room       ┆ to home    │
│ …           ┆ …      ┆ …       ┆ …      ┆ … ┆ …          ┆ …           ┆ …          ┆ …          │
│ null        ┆ null   ┆ null    ┆ null   ┆ … ┆ null       ┆ null        ┆ Premature  ┆ null       │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ Delivery   ┆            │
│ null        ┆ null   ┆ null    ┆ null   ┆ … ┆ null       ┆ null        ┆ null       ┆ Unknown/In │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ valid      │
│ null        ┆ null   ┆ null    ┆ null   ┆ … ┆ null       ┆ null        ┆ null       ┆ Discharged │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ /transferr │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ ed to a    │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ Cr…        │
│ null        ┆ null   ┆ null    ┆ null   ┆ … ┆ null       ┆ null        ┆ null       ┆ Discharged │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ /transferr │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ ed to      │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ anot…      │
│ null        ┆ null   ┆ null    ┆ null   ┆ … ┆ null       ┆ null        ┆ null       ┆ Expired;   │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ place      │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ unknown.   │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ Medica…    │
└─────────────┴────────┴─────────┴────────┴───┴────────────┴─────────────┴────────────┴────────────┘

In [179]:
# Delete null rows
df.filter(~pl.any_horizontal(pl.all().is_null()))

shape: (101_766, 48)
┌─────────────┬────────┬─────────┬────────┬───┬────────────┬─────────────┬────────────┬────────────┐
│ race        ┆ gender ┆ age     ┆ weight ┆ … ┆ readmitted ┆ admission_t ┆ admission_ ┆ discharge_ │
│ ---         ┆ ---    ┆ ---     ┆ ---    ┆   ┆ ---        ┆ ype         ┆ source     ┆ dispositio │
│ str         ┆ str    ┆ str     ┆ str    ┆   ┆ str        ┆ ---         ┆ ---        ┆ n          │
│             ┆        ┆         ┆        ┆   ┆            ┆ str         ┆ str        ┆ ---        │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ str        │
╞═════════════╪════════╪═════════╪════════╪═══╪════════════╪═════════════╪════════════╪════════════╡
│ Caucasian   ┆ Female ┆ [0-10)  ┆ ?      ┆ … ┆ NO         ┆ NULL        ┆ Physician  ┆ Not Mapped │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ Referral   ┆            │
│ Caucasian   ┆ Female ┆ [10-20) ┆ ?      ┆ … ┆ >30        ┆ Emergency   ┆ Emergency  ┆ Discharged │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ Room       ┆ to home    │
│ AfricanAmer ┆ Female ┆ [20-30) ┆ ?      ┆ … ┆ NO         ┆ Emergency   ┆ Emergency  ┆ Discharged │
│ ican        ┆        ┆         ┆        ┆   ┆            ┆             ┆ Room       ┆ to home    │
│ Caucasian   ┆ Male   ┆ [30-40) ┆ ?      ┆ … ┆ NO         ┆ Emergency   ┆ Emergency  ┆ Discharged │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ Room       ┆ to home    │
│ Caucasian   ┆ Male   ┆ [40-50) ┆ ?      ┆ … ┆ NO         ┆ Emergency   ┆ Emergency  ┆ Discharged │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ Room       ┆ to home    │
│ …           ┆ …      ┆ …       ┆ …      ┆ … ┆ …          ┆ …           ┆ …          ┆ …          │
│ AfricanAmer ┆ Male   ┆ [70-80) ┆ ?      ┆ … ┆ >30        ┆ Emergency   ┆ Emergency  ┆ Discharged │
│ ican        ┆        ┆         ┆        ┆   ┆            ┆             ┆ Room       ┆ /transferr │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ ed to SNF  │
│ AfricanAmer ┆ Female ┆ [80-90) ┆ ?      ┆ … ┆ NO         ┆ Emergency   ┆ Transfer   ┆ Discharged │
│ ican        ┆        ┆         ┆        ┆   ┆            ┆             ┆ from a     ┆ /transferr │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ Skilled    ┆ ed to ICF  │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ Nursin…    ┆            │
│ Caucasian   ┆ Male   ┆ [70-80) ┆ ?      ┆ … ┆ NO         ┆ Emergency   ┆ Emergency  ┆ Discharged │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ Room       ┆ to home    │
│ Caucasian   ┆ Female ┆ [80-90) ┆ ?      ┆ … ┆ NO         ┆ Urgent      ┆ Emergency  ┆ Discharged │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ Room       ┆ /transferr │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆            ┆ ed to SNF  │
│ Caucasian   ┆ Male   ┆ [70-80) ┆ ?      ┆ … ┆ NO         ┆ Emergency   ┆ Emergency  ┆ Discharged │
│             ┆        ┆         ┆        ┆   ┆            ┆             ┆ Room       ┆ to home    │
└─────────────┴────────┴─────────┴────────┴───┴────────────┴─────────────┴────────────┴────────────┘

In [180]:
df = df.filter(~pl.any_horizontal(pl.all().is_null()))

In [185]:
df = df.with_columns(
    age = (
        pl.col("age")
        .str.extract_all(r"\d+")  # Extracts all digits as a list of strings
        .list.get(0).cast(pl.Float64) + 
        pl.col("age")
        .str.extract_all(r"\d+")
        .list.get(1).cast(pl.Int64)
    ) / 2
)

In [186]:
df

shape: (101_766, 48)
┌──────────────┬────────┬──────┬────────┬───┬────────────┬─────────────┬─────────────┬─────────────┐
│ race         ┆ gender ┆ age  ┆ weight ┆ … ┆ readmitted ┆ admission_t ┆ admission_s ┆ discharge_d │
│ ---          ┆ ---    ┆ ---  ┆ ---    ┆   ┆ ---        ┆ ype         ┆ ource       ┆ isposition  │
│ str          ┆ str    ┆ f64  ┆ str    ┆   ┆ str        ┆ ---         ┆ ---         ┆ ---         │
│              ┆        ┆      ┆        ┆   ┆            ┆ str         ┆ str         ┆ str         │
╞══════════════╪════════╪══════╪════════╪═══╪════════════╪═════════════╪═════════════╪═════════════╡
│ Caucasian    ┆ Female ┆ 5.0  ┆ ?      ┆ … ┆ NO         ┆ NULL        ┆ Physician   ┆ Not Mapped  │
│              ┆        ┆      ┆        ┆   ┆            ┆             ┆ Referral    ┆             │
│ Caucasian    ┆ Female ┆ 15.0 ┆ ?      ┆ … ┆ >30        ┆ Emergency   ┆ Emergency   ┆ Discharged  │
│              ┆        ┆      ┆        ┆   ┆            ┆             ┆ Room        ┆ to home     │
│ AfricanAmeri ┆ Female ┆ 25.0 ┆ ?      ┆ … ┆ NO         ┆ Emergency   ┆ Emergency   ┆ Discharged  │
│ can          ┆        ┆      ┆        ┆   ┆            ┆             ┆ Room        ┆ to home     │
│ Caucasian    ┆ Male   ┆ 35.0 ┆ ?      ┆ … ┆ NO         ┆ Emergency   ┆ Emergency   ┆ Discharged  │
│              ┆        ┆      ┆        ┆   ┆            ┆             ┆ Room        ┆ to home     │
│ Caucasian    ┆ Male   ┆ 45.0 ┆ ?      ┆ … ┆ NO         ┆ Emergency   ┆ Emergency   ┆ Discharged  │
│              ┆        ┆      ┆        ┆   ┆            ┆             ┆ Room        ┆ to home     │
│ …            ┆ …      ┆ …    ┆ …      ┆ … ┆ …          ┆ …           ┆ …           ┆ …           │
│ AfricanAmeri ┆ Male   ┆ 75.0 ┆ ?      ┆ … ┆ >30        ┆ Emergency   ┆ Emergency   ┆ Discharged/ │
│ can          ┆        ┆      ┆        ┆   ┆            ┆             ┆ Room        ┆ transferred │
│              ┆        ┆      ┆        ┆   ┆            ┆             ┆             ┆ to SNF      │
│ AfricanAmeri ┆ Female ┆ 85.0 ┆ ?      ┆ … ┆ NO         ┆ Emergency   ┆ Transfer    ┆ Discharged/ │
│ can          ┆        ┆      ┆        ┆   ┆            ┆             ┆ from a      ┆ transferred │
│              ┆        ┆      ┆        ┆   ┆            ┆             ┆ Skilled     ┆ to ICF      │
│              ┆        ┆      ┆        ┆   ┆            ┆             ┆ Nursin…     ┆             │
│ Caucasian    ┆ Male   ┆ 75.0 ┆ ?      ┆ … ┆ NO         ┆ Emergency   ┆ Emergency   ┆ Discharged  │
│              ┆        ┆      ┆        ┆   ┆            ┆             ┆ Room        ┆ to home     │
│ Caucasian    ┆ Female ┆ 85.0 ┆ ?      ┆ … ┆ NO         ┆ Urgent      ┆ Emergency   ┆ Discharged/ │
│              ┆        ┆      ┆        ┆   ┆            ┆             ┆ Room        ┆ transferred │
│              ┆        ┆      ┆        ┆   ┆            ┆             ┆             ┆ to SNF      │
│ Caucasian    ┆ Male   ┆ 75.0 ┆ ?      ┆ … ┆ NO         ┆ Emergency   ┆ Emergency   ┆ Discharged  │
│              ┆        ┆      ┆        ┆   ┆            ┆             ┆ Room        ┆ to home     │
└──────────────┴────────┴──────┴────────┴───┴────────────┴─────────────┴─────────────┴─────────────┘

In [188]:
df['max_glu_serum'].unique()

shape: (4,)
Series: 'max_glu_serum' [str]
[
	"Norm"
	"None"
	">200"
	">300"
]