In [6]:
import polars as pl
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [7]:
df = pl.read_csv("../hospital_readmission_dataset.csv")
df.head()

shape: (5, 17)
┌────────────┬──────────────┬────────┬─────┬───┬──────────────┬──────────────┬─────────────┬───────┐
│ patient_id ┆ admission_da ┆ season ┆ age ┆ … ┆ insurance_ty ┆ discharge_di ┆ readmission ┆ label │
│ ---        ┆ te           ┆ ---    ┆ --- ┆   ┆ pe           ┆ sposition    ┆ _risk_score ┆ ---   │
│ str        ┆ ---          ┆ str    ┆ i64 ┆   ┆ ---          ┆ ---          ┆ ---         ┆ i64   │
│            ┆ str          ┆        ┆     ┆   ┆ str          ┆ str          ┆ f64         ┆       │
╞════════════╪══════════════╪════════╪═════╪═══╪══════════════╪══════════════╪═════════════╪═══════╡
│ P00001     ┆ 2022-04-14   ┆ Spring ┆ 66  ┆ … ┆ Medicare     ┆ Home Health  ┆ 0.92        ┆ 1     │
│ P00002     ┆ 2021-09-19   ┆ Fall   ┆ 55  ┆ … ┆ Private      ┆ Home Health  ┆ 0.88        ┆ 1     │
│ P00003     ┆ 2023-04-12   ┆ Spring ┆ 69  ┆ … ┆ Medicare     ┆ Skilled      ┆ 0.97        ┆ 1     │
│            ┆              ┆        ┆     ┆   ┆              ┆ Nursing      ┆             ┆       │
│ P00004     ┆ 2023-08-14   ┆ Summer ┆ 83  ┆ … ┆ Medicare     ┆ Skilled      ┆ 0.97        ┆ 1     │
│            ┆              ┆        ┆     ┆   ┆              ┆ Nursing      ┆             ┆       │
│ P00005     ┆ 2021-11-05   ┆ Fall   ┆ 54  ┆ … ┆ Uninsured    ┆ Home Health  ┆ 0.83        ┆ 1     │
└────────────┴──────────────┴────────┴─────┴───┴──────────────┴──────────────┴─────────────┴───────┘

In [8]:
df.describe()

shape: (9, 18)
┌────────────┬────────────┬────────────┬────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic  ┆ patient_id ┆ admission_ ┆ season ┆ … ┆ insurance ┆ discharge ┆ readmissi ┆ label    │
│ ---        ┆ ---        ┆ date       ┆ ---    ┆   ┆ _type     ┆ _disposit ┆ on_risk_s ┆ ---      │
│ str        ┆ str        ┆ ---        ┆ str    ┆   ┆ ---       ┆ ion       ┆ core      ┆ f64      │
│            ┆            ┆ str        ┆        ┆   ┆ str       ┆ ---       ┆ ---       ┆          │
│            ┆            ┆            ┆        ┆   ┆           ┆ str       ┆ f64       ┆          │
╞════════════╪════════════╪════════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count      ┆ 8000       ┆ 8000       ┆ 8000   ┆ … ┆ 8000      ┆ 8000      ┆ 8000.0    ┆ 8000.0   │
│ null_count ┆ 0          ┆ 0          ┆ 0      ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0      │
│ mean       ┆ null       ┆ null       ┆ null   ┆ … ┆ null      ┆ null      ┆ 0.7769375 ┆ 0.772875 │
│ std        ┆ null       ┆ null       ┆ null   ┆ … ┆ null      ┆ null      ┆ 0.219885  ┆ 0.419    │
│ min        ┆ P00001     ┆ 2021-01-01 ┆ Fall   ┆ … ┆ Medicaid  ┆ Home      ┆ 0.07      ┆ 0.0      │
│ 25%        ┆ null       ┆ null       ┆ null   ┆ … ┆ null      ┆ null      ┆ 0.63      ┆ 1.0      │
│ 50%        ┆ null       ┆ null       ┆ null   ┆ … ┆ null      ┆ null      ┆ 0.86      ┆ 1.0      │
│ 75%        ┆ null       ┆ null       ┆ null   ┆ … ┆ null      ┆ null      ┆ 0.97      ┆ 1.0      │
│ max        ┆ P08000     ┆ 2023-12-31 ┆ Winter ┆ … ┆ Uninsured ┆ Skilled   ┆ 0.97      ┆ 1.0      │
│            ┆            ┆            ┆        ┆   ┆           ┆ Nursing   ┆           ┆          │
└────────────┴────────────┴────────────┴────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
X = df.drop(['label'])
y = df['label']

# Define column groups
numerical_cols = [
    'age', 'comorbidities_count', 'length_of_stay',
    'medications_count', 'followup_visits_last_year',
    'prev_readmissions', 'readmission_risk_score'
]
categorical_cols = [
    'season', 'gender', 'region', 'primary_diagnosis',
    'treatment_type', 'insurance_type', 'discharge_disposition'
]

In [10]:
# Split Test and Training data
# Convert polars DataFrame and Series to pandas DataFrame and Series
X_train, X_test, y_train, y_test = train_test_split(X.to_pandas(),
                                                    y.to_pandas(),
                                                    test_size=0.2,
                                                    random_state=42,
                                                    stratify=y)

In [12]:
# Build preprocessing pipeline
preprocessor = ColumnTransformer(transformers=[
    ('num', RobustScaler(), numerical_cols),
    ('cat', OneHotEncoder(drop='first', handle_unknown='ignore', sparse_output=False), categorical_cols)
])

# Fit on train only, transform both
X_train_scaled = preprocessor.fit_transform(X_train)
X_test_scaled  = preprocessor.transform(X_test)

In [16]:
pl.DataFrame(X_train_scaled).describe()

shape: (9, 35)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ column_0  ┆ column_1 ┆ column_2  ┆ … ┆ column_30 ┆ column_31 ┆ column_32 ┆ column_33 │
│ ---       ┆ ---       ┆ ---      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str       ┆ f64       ┆ f64      ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 6400.0    ┆ 6400.0   ┆ 6400.0    ┆ … ┆ 6400.0    ┆ 6400.0    ┆ 6400.0    ┆ 6400.0    │
│ null_coun ┆ 0.0       ┆ 0.0      ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ t         ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ 0.020136  ┆ 0.16125  ┆ -0.066771 ┆ … ┆ 0.099375  ┆ 0.754531  ┆ 0.006406  ┆ 0.19875   │
│ std       ┆ 0.732484  ┆ 0.683461 ┆ 0.643381  ┆ … ┆ 0.299188  ┆ 0.430398  ┆ 0.079788  ┆ 0.399091  │
│ min       ┆ -1.695652 ┆ -1.5     ┆ -1.666667 ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 25%       ┆ -0.478261 ┆ -0.5     ┆ -0.666667 ┆ … ┆ 0.0       ┆ 1.0       ┆ 0.0       ┆ 0.0       │
│ 50%       ┆ 0.0       ┆ 0.0      ┆ 0.0       ┆ … ┆ 0.0       ┆ 1.0       ┆ 0.0       ┆ 0.0       │
│ 75%       ┆ 0.521739  ┆ 0.5      ┆ 0.333333  ┆ … ┆ 0.0       ┆ 1.0       ┆ 0.0       ┆ 0.0       │
│ max       ┆ 1.652174  ┆ 3.0      ┆ 2.333333  ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0       │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘